# Pulling metadata information from maps layers, Group Layers and its Sublayers.  
I am hoping to use the outcome of this data to be a simple DB in ESRI -> Connected to Survey123 -> Make it at least html-like style.

In [11]:
from arcgis.gis import GIS
import pandas as pd
from dotenv import load_dotenv
import os
import json

load_dotenv()

signin_name = os.getenv('ESRI_USERNAME')
signin_password = os.getenv('ESRI_PASSWORD')
signin_link = os.getenv("HUBLINK")

# Connect to the organization
gis = GIS(signin_link, signin_name, signin_password )
username = gis.users.me.username

print("Done")

Done

In [12]:
maps = {
	'natural-treasures': {
		'title': 'Natural Treasures',
		'mapId': 'aba702c5420e4a36ac645f14a00ba8f1'
	},
	'transportation-infrastructure': {
		'title': 'Transportation + Infrastructure',
		'mapId': '25c75ac490b94b85b02aa4fd2f341fbb'
	}
}

## Find layer metadata - nested

In [4]:
skip_titles = {'Thrive County Boundaries','Thrive watershed region', 'waterbodies'}

rows = []

for slug, m in maps.items():
    map_item = gis.content.get(m['mapId'])
    wm = map_item.get_data()
    for top in wm.get('operationalLayers', []):
        top_title = str(top.get('title'))
        if top_title in skip_titles:
            continue
        is_group = top.get('layerType') == 'GroupLayer'
        if is_group and not top.get('layers'):
            continue
        group = top_title if is_group else ''
        for lyr in (top.get('layers') or []) if is_group else [top]:
            layer_title = str(lyr.get('title'))
            if layer_title in skip_titles:
                continue
            url = lyr.get('url') or ''
            # one row per map entry, plus one row for the service layer that entry draws.
            # the entry url ends in that layer's index, so no item.layers call is needed here
            # and nothing gets repeated under the wrong parent. image services have no index.
            tail = url.rstrip('/').split('/')[-1]
            base = {
                'map_slug': slug,
                'map_title': m['title'],
                'map_id': m['mapId'],
                'group': group,
                'layer_title': layer_title,
                'layer_type': lyr.get('layerType'),
                'item_id': lyr.get('itemId'),
                'url': url,
            }
            rows.append({**base, 'level': 'layer',
                         'sublayer_id': None, 'sublayer_name': None})
            if tail.isdigit():
                rows.append({**base, 'level': 'sublayer',
                             'sublayer_id': int(tail), 'sublayer_name': None})

df = pd.DataFrame(rows)
print(len(df), 'rows |', (df.level == 'layer').sum(), 'layer |', (df.level == 'sublayer').sum(), 'sublayer |',
      df.item_id.nunique(), 'unique items |',
      df[['item_id', 'sublayer_id']].dropna().drop_duplicates().shape[0], 'unique item+sublayer pairs')
df

170 rows | 92 layer | 78 sublayer | 47 unique items | 71 unique item+sublayer pairs

,map_slug,map_title,map_id,group,layer_title,layer_type,item_id,url,level,sublayer_id,sublayer_name
0,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Cross Sector Data,parcels,GroupLayer,NaN,,layer,NaN,None
1,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Cross Sector Data,Tax Parcel Boundaries,ArcGISTiledMapServiceLayer,a2050b09baff493aa4ad7848ba2fac00,https://tiles.arcgis.com/tiles/KzeiCaQsMoeCfoC...,layer,NaN,None
2,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Cross Sector Data,Population Change 2000-2020,ArcGISFeatureLayer,5239d5d3ea5f4d13a325ad0184377963,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/...,layer,NaN,None
3,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Cross Sector Data,Population Change 2000-2020,ArcGISFeatureLayer,5239d5d3ea5f4d13a325ad0184377963,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/...,sublayer,34.0,None
4,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Land Use,Developed Land Change,ArcGISFeatureLayer,c8cb5376347542f597437060984d4069,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/...,layer,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...
165,transportation-infrastructure,Transportation + Infrastructure,25c75ac490b94b85b02aa4fd2f341fbb,Thrive boundaries and mask layers,thrive_primary_region_mask,ArcGISFeatureLayer,c8535d9ac4fd485b8a7e88a70dd2cbc7,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/...,layer,NaN,None
166,transportation-infrastructure,Transportation + Infrastructure,25c75ac490b94b85b02aa4fd2f341fbb,Thrive boundaries and mask layers,thrive_primary_region_mask,ArcGISFeatureLayer,c8535d9ac4fd485b8a7e88a70dd2cbc7,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/...,sublayer,0.0,None
167,transportation-infrastructure,Transportation + Infrastructure,25c75ac490b94b85b02aa4fd2f341fbb,Thrive boundaries and mask layers,thrive_secondary_boundary,ArcGISFeatureLayer,562632e4f4c447ff9f1accd4a7640bb6,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/...,layer,NaN,None
168,transportation-infrastructure,Transportation + Infrastructure,25c75ac490b94b85b02aa4fd2f341fbb,Thrive boundaries and mask layers,thrive_secondary_boundary,ArcGISFeatureLayer,562632e4f4c447ff9f1accd4a7640bb6,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/...,sublayer,0.0,None
169,transportation-infrastructure,Transportation + Infrastructure,25c75ac490b94b85b02aa4fd2f341fbb,Thrive boundaries and mask layers,Thrive Counties,GeoJSON,f97879f1e2b3463597ad7a0e43248d92,https://www.arcgis.com/sharing/rest/content/it...,layer,NaN,None

In [5]:
# test every item in the list: its text, and the rows that carry it
for iid in df['item_id'].dropna().unique():
    item = gis.content.get(iid)
    print('=' * 88)
    if item is None:
        print(iid, '-> the item did not come back')
        continue
    print(iid, '|', item.get('title'), '|', item.get('owner'), '|', item.get('access'))
    print('  summary        :', repr(item.get('snippet'))[:70])
    print('  description    :', repr(item.get('description'))[:70])
    print('  acknowledgments:', repr(item.get('accessInformation'))[:70])
    for r in df[df.item_id == iid].itertuples():
        if pd.isna(r.sublayer_id):
            link = f"{gis.url}/home/item.html?id={iid}"
        else:
            link = f"{gis.url}/home/item.html?id={iid}&sublayer={int(r.sublayer_id)}"
        print(f'    {r.level:8s} | {str(r.layer_title)[:42]:42s} | {link}')

========================================================================================
a2050b09baff493aa4ad7848ba2fac00 | Regrid USA Nationwide Parcel Boundaries | data_regrid | public
  summary        : 'Regrid Nationwide Parcel Boundaries for the United States.\n'
  description    : '<p style=\'text-align:center;\'><a target=\'_blank\' href=\'https://w
  acknowledgments: 'Regrid'
    layer    | Tax Parcel Boundaries                      | https://thrive-geohub.maps.arcgis.com/home/item.html?id=a2050b09baff493aa4ad7848ba2fac00
    layer    | Regrid USA Nationwide Parcel Boundaries    | https://thrive-geohub.maps.arcgis.com/home/item.html?id=a2050b09baff493aa4ad7848ba2fac00
========================================================================================
5239d5d3ea5f4d13a325ad0184377963 | Population Change by Tract (2000-2020) | sara2263_thrive_geohub | public
  summary        : None
  description    : None
  acknowledgments: None
    layer    | Population Change 2000-2020                | https://thrive-geohub.maps.arcgis.com/home/item.html?id=5239d5d3ea5f4d13a325ad0184377963
    sublayer | Population Change 2000-2020                | https://thrive-geohub.maps.arcgis.com/home/item.html?id=5239d5d3ea5f4d13a325ad0184377963&sublayer=34
========================================================================================
c8cb5376347542f597437060984d4069 | landcover change watershed 1 mile hex grid | sara2263_thrive_geohub | public
  summary        : 'Land use change aggregated to 1 mile hex bins (2004–2024)'
  description    : None
  acknowledgments: None
    layer    | Developed Land Change                      | https://thrive-geohub.maps.arcgis.com/home/item.html?id=c8cb5376347542f597437060984d4069
    sublayer | Developed Land Change                      | https://thrive-geohub.maps.arcgis.com/home/item.html?id=c8cb5376347542f597437060984d4069&sublayer=0
    layer    | Natural Cover Change                       | https://thrive-geohub.maps.arcgis.com/home/item.html?id=c8cb5376347542f597437060984d4069
    sublayer | Natural Cover Change                       | https://thrive-geohub.maps.arcgis.com/home/item.html?id=c8cb5376347542f597437060984d4069&sublayer=0
    layer    | Agricultural Land Change                   | https://thrive-geohub.maps.arcgis.com/home/item.html?id=c8cb5376347542f597437060984d4069
    sublayer | Agricultural Land Change                   | https://thrive-geohub.maps.arcgis.com/home/item.html?id=c8cb5376347542f597437060984d4069&sublayer=0
========================================================================================
d54eeaddbc3e442eae779aacc06fdf7c | landuse_change_watershed_boundary_2004_2024_60m | sara2263_thrive_geohub | public
  summary        : ''
  description    : ''
  acknowledgments: ''
    layer    | Land Use Change 2004 – 2024 60 meter resol | https://thrive-geohub.maps.arcgis.com/home/item.html?id=d54eeaddbc3e442eae779aacc06fdf7c
========================================================================================
13c415b776c0463e863f89361ed688da | Future Land Cover, 2050 | sara2263_thrive_geohub | public
  summary        : 'Land use modeled to represent possible changes. Learn more about the
  description    : '<p>Predicted land cover for each country for year 2050, generated by
  acknowledgments: None
    layer    | Future Land Cover: 2050                    | https://thrive-geohub.maps.arcgis.com/home/item.html?id=13c415b776c0463e863f89361ed688da
========================================================================================
49f5a7a36df7476fb13a1daec41f8714 | thrive_watershed_huc10_boundary | sara2263_thrive_geohub | public
  summary        : None
  description    : None
  acknowledgments: None
    layer    | mask                                       | https://thrive-geohub.maps.arcgis.com/home/item.html?id=49f5a7a36df7476fb13a1daec41f8714
    sublayer | mask                                       | https://thrive-geohub.maps.arcgis.com/home/item.html?id=49f5a7a36df7476fb13a1daec41f8714&sublayer=0
========================================================================================
7832080ff813443db6156aa7d6c905c8 | Thrive Agricultural Suitability Model 2026 | vqq585_mymocs | public
  summary        : 'This version of the 2026 Thrive Agricultural Suitability Model has ha
  description    : '<p>This version of the 2026 Thrive Agricultural Suitability Model has
  acknowledgments: None
    layer    | Suitability of Land for Agriculture        | https://thrive-geohub.maps.arcgis.com/home/item.html?id=7832080ff813443db6156aa7d6c905c8
========================================================================================
90500e937941425abb5f91f8c727f72a | Cradle Region Invasive Species Observations (Watershed Boundary) | GZG367_IGTLab | public
  summary        : 'Consolidated invasive species observation records for the Thrive regi
  description    : "<p><strong>Overview</strong></p><p style='background-color:rgb(255, 2
  acknowledgments: 'EDDMapS'
    layer    | Invasive Species Observations              | https://thrive-geohub.maps.arcgis.com/home/item.html?id=90500e937941425abb5f91f8c727f72a
    sublayer | Invasive Species Observations              | https://thrive-geohub.maps.arcgis.com/home/item.html?id=90500e937941425abb5f91f8c727f72a&sublayer=0
========================================================================================
2409942bd2b143059b4b15bc018bce4a | Thrive Cradle Imperiled Species Zonal Statistics | vqq585_mymocs | public
  summary        : 'Hexagon-based zonal statistics summarizing imperiled species richness
  description    : "<p><strong>Overview</strong></p><p>This feature service provides hexa
  acknowledgments: ''
    layer    | Threatened Species                         | https://thrive-geohub.maps.arcgis.com/home/item.html?id=2409942bd2b143059b4b15bc018bce4a
    sublayer | Threatened Species                         | https://thrive-geohub.maps.arcgis.com/home/item.html?id=2409942bd2b143059b4b15bc018bce4a&sublayer=0
========================================================================================
e0ec4650fa8f4f59a016baf36937125e | Thrive Cradle Habitat Cores 2026 | vqq585_mymocs | public
  summary        : 'Thematic raster of modeled intact habitat cores for the Thrive Cradle
  description    : "<p><strong>Overview</strong></p><p>This Image Service provides a them
  acknowledgments: "Esri's Green Infrastructure Initiative"
    layer    | Intact Habitat Cores                       | https://thrive-geohub.maps.arcgis.com/home/item.html?id=e0ec4650fa8f4f59a016baf36937125e
========================================================================================
0edfcf9c2014474fab8a9d5bab2c9084 | Protected Lands in the Cradle of Southern Appalachia (2026) | vqq585_mymocs | public
  summary        : 'This service delivers detailed spatial data on protected lands in the
  description    : "<p><strong>Overview</strong></p><p>This feature service provides deta
  acknowledgments: ''
    layer    | Protected Lands                            | https://thrive-geohub.maps.arcgis.com/home/item.html?id=0edfcf9c2014474fab8a9d5bab2c9084
    sublayer | Protected Lands                            | https://thrive-geohub.maps.arcgis.com/home/item.html?id=0edfcf9c2014474fab8a9d5bab2c9084&sublayer=0
========================================================================================
c6c00112223c4412a93fed76a8086ef9 | PALD_thrive_region_farmland_trust_2025 | sara2263_thrive_geohub | public
  summary        : 'Farmland that has been preserved by placement into a land trust; Amer
  description    : '<p>Data provided by Casey Mitchell at Farmland Trust (cmitchell@farml
  acknowledgments: None
    layer    | Protected Farmland                         | https://thrive-geohub.maps.arcgis.com/home/item.html?id=c6c00112223c4412a93fed76a8086ef9
    sublayer | Protected Farmland                         | https://thrive-geohub.maps.arcgis.com/home/item.html?id=c6c00112223c4412a93fed76a8086ef9&sublayer=0
========================================================================================
abd42c2259f04ae886d83cfe3f8bdfc7 | Landscape Conservation Priority Model | cmix0085 | public
  summary        : "This map ranks the landscape based on intact habitat cores, corridors
  description    : "<p>This map ranks the landscape based on intact habitat cores, corrid
  acknowledgments: ''
    layer    | Conservation Priority Areas                | https://thrive-geohub.maps.arcgis.com/home/item.html?id=abd42c2259f04ae886d83cfe3f8bdfc7
    sublayer | Conservation Priority Areas                | https://thrive-geohub.maps.arcgis.com/home/item.html?id=abd42c2259f04ae886d83cfe3f8bdfc7&sublayer=0
========================================================================================
7329aefb41374f19b288158261969e56 | Thrive Region 303d Stream Segments (2025) | vqq585_mymocs | public
  summary        : 'USA Impaired or Threatened Waterbodies (303d) stream segments for the
  description    : '<p>This dataset reflects the Thrive Cradle regions 303d listed stream
  acknowledgments: ''
    layer    | Stream health                              | https://thrive-geohub.maps.arcgis.com/home/item.html?id=7329aefb41374f19b288158261969e56
    sublayer | Stream health                              | https://thrive-geohub.maps.arcgis.com/home/item.html?id=7329aefb41374f19b288158261969e56&sublayer=0
    layer    | Stream health ratings (2025)               | https://thrive-geohub.maps.arcgis.com/home/item.html?id=7329aefb41374f19b288158261969e56
    sublayer | Stream health ratings (2025)               | https://thrive-geohub.maps.arcgis.com/home/item.html?id=7329aefb41374f19b288158261969e56&sublayer=0
========================================================================================
78fec49ff3e4442dbe265a1c2be605e1 | Waterbody Health | sara2263_thrive_geohub | public
  summary        : 'As part of the Clean Water Act, waterbodies are assessed nationwide e
  description    : None
  acknowledgments: None
    layer    | Waterbody health                           | https://thrive-geohub.maps.arcgis.com/home/item.html?id=78fec49ff3e4442dbe265a1c2be605e1
    sublayer | Waterbody health                           | https://thrive-geohub.maps.arcgis.com/home/item.html?id=78fec49ff3e4442dbe265a1c2be605e1&sublayer=0
========================================================================================
5197c7e3bc0b4810a4afa8b62020c357 | FRS_INTERESTS_ACRES | sara2263_thrive_geohub | public
  summary        : 'Sites identified by the EPA Facility Registry Service (FRS). Brownfie
  description    : "<p>Descrption Field text test: styling possible here: Brownfield site
  acknowledgments: None
    layer    | Brownfield Sites                           | https://thrive-geohub.maps.arcgis.com/home/item.html?id=5197c7e3bc0b4810a4afa8b62020c357
    sublayer | Brownfield Sites                           | https://thrive-geohub.maps.arcgis.com/home/item.html?id=5197c7e3bc0b4810a4afa8b62020c357&sublayer=0
========================================================================================
8d81d6bdada5418c95365b0dabea2747 | FRS_INTERESTS_SEMS | sara2263_thrive_geohub | public
  summary        : 'Hazardous waste sites evaluated by the federal Superfund program. Sta
  description    : 'SEMS'
  acknowledgments: None
    layer    | Superfund sites                            | https://thrive-geohub.maps.arcgis.com/home/item.html?id=8d81d6bdada5418c95365b0dabea2747
    sublayer | Superfund sites                            | https://thrive-geohub.maps.arcgis.com/home/item.html?id=8d81d6bdada5418c95365b0dabea2747&sublayer=0
========================================================================================
f98b736071c64dc99a72f9e54120d7b4 | HUC10 Watersheds of Thrive | sara2263_thrive_geohub | public
  summary        : 'HUC 10 Watersheds of the greater Chattanooga region. '
  description    : 'HUC 10s of the Cradle of Southern Appalachia Conservation Project.\xa
  acknowledgments: ''
    layer    | Watershed boundaries                       | https://thrive-geohub.maps.arcgis.com/home/item.html?id=f98b736071c64dc99a72f9e54120d7b4
========================================================================================
73ed3c78493a4abd8142d9d3038c6a0d | parks public access 3857 20260928 | sara2263_thrive_geohub | public
  summary        : 'Publicly acessible parks and nature reserves. '
  description    : None
  acknowledgments: None
    layer    | Parks and Nature Reserves                  | https://thrive-geohub.maps.arcgis.com/home/item.html?id=73ed3c78493a4abd8142d9d3038c6a0d
    sublayer | Parks and Nature Reserves                  | https://thrive-geohub.maps.arcgis.com/home/item.html?id=73ed3c78493a4abd8142d9d3038c6a0d&sublayer=0
========================================================================================
18cacd1713e245b9916b53b7ef52f416 | trails_county_name_added | sara2263_thrive_geohub | public
  summary        : None
  description    : None
  acknowledgments: None
    layer    | Hiking Trails                              | https://thrive-geohub.maps.arcgis.com/home/item.html?id=18cacd1713e245b9916b53b7ef52f416
    sublayer | Hiking Trails                              | https://thrive-geohub.maps.arcgis.com/home/item.html?id=18cacd1713e245b9916b53b7ef52f416&sublayer=0
========================================================================================
48621d7af80e4b6cbcacf17afbfc6507 | river_access_points_20260913 | sara2263_thrive_geohub | public
  summary        : 'Sites where the public can access the water or launch a boat. '
  description    : None
  acknowledgments: None
    layer    | River Access                               | https://thrive-geohub.maps.arcgis.com/home/item.html?id=48621d7af80e4b6cbcacf17afbfc6507
    sublayer | River Access                               | https://thrive-geohub.maps.arcgis.com/home/item.html?id=48621d7af80e4b6cbcacf17afbfc6507&sublayer=0
========================================================================================
cded33c61c134ff897f35442126aed47 | NHD_waterbodies_Thrive_region_simplified | sara2263_thrive_geohub | public
  summary        : 'includes NHD waterbodies larger than .5 sq km'
  description    : None
  acknowledgments: None
    layer    | NHD Waterbodies                            | https://thrive-geohub.maps.arcgis.com/home/item.html?id=cded33c61c134ff897f35442126aed47
========================================================================================
1973d4a4c57f4750aa04a4046db6aebe | Chattanooga Regional Trails | sara2263_thrive_geohub | public
  summary        : 'Recreation trails in the Chattanooga, Tennessee region.'
  description    : '<p>Recreational trails within the Chattanooga, Tennessee region. Trai
  acknowledgments: ''
    layer    | Chattanooga Regional Trails                | https://thrive-geohub.maps.arcgis.com/home/item.html?id=1973d4a4c57f4750aa04a4046db6aebe
========================================================================================
27ae7a909af64bdaa3181b444c65e23b | landuse_Change_1miGrid_Calc | sara2263_thrive_geohub | public
  summary        : None
  description    : None
  acknowledgments: None
    layer    | Developed Land increase percentage 2004-20 | https://thrive-geohub.maps.arcgis.com/home/item.html?id=27ae7a909af64bdaa3181b444c65e23b
    sublayer | Developed Land increase percentage 2004-20 | https://thrive-geohub.maps.arcgis.com/home/item.html?id=27ae7a909af64bdaa3181b444c65e23b&sublayer=0
    layer    | Increased Natural Cover 2004-2024          | https://thrive-geohub.maps.arcgis.com/home/item.html?id=27ae7a909af64bdaa3181b444c65e23b
    sublayer | Increased Natural Cover 2004-2024          | https://thrive-geohub.maps.arcgis.com/home/item.html?id=27ae7a909af64bdaa3181b444c65e23b&sublayer=0
    layer    | Developed land increase                    | https://thrive-geohub.maps.arcgis.com/home/item.html?id=27ae7a909af64bdaa3181b444c65e23b
    sublayer | Developed land increase                    | https://thrive-geohub.maps.arcgis.com/home/item.html?id=27ae7a909af64bdaa3181b444c65e23b&sublayer=0
    layer    | Landuse Change 2004-2024                   | https://thrive-geohub.maps.arcgis.com/home/item.html?id=27ae7a909af64bdaa3181b444c65e23b
    sublayer | Landuse Change 2004-2024                   | https://thrive-geohub.maps.arcgis.com/home/item.html?id=27ae7a909af64bdaa3181b444c65e23b&sublayer=0
    layer    | Increased Natural Cover 2004-2024          | https://thrive-geohub.maps.arcgis.com/home/item.html?id=27ae7a909af64bdaa3181b444c65e23b
    sublayer | Increased Natural Cover 2004-2024          | https://thrive-geohub.maps.arcgis.com/home/item.html?id=27ae7a909af64bdaa3181b444c65e23b&sublayer=0
========================================================================================
d90313e1488047759b7539689aae53fa | LancoverChangeGrids | sara2263_thrive_geohub | public
  summary        : None
  description    : None
  acknowledgments: None
    layer    | LancoverChangeGrids                        | https://thrive-geohub.maps.arcgis.com/home/item.html?id=d90313e1488047759b7539689aae53fa
    sublayer | LancoverChangeGrids                        | https://thrive-geohub.maps.arcgis.com/home/item.html?id=d90313e1488047759b7539689aae53fa&sublayer=0
========================================================================================
f36951b64bac47fdbcce339abbd39085 | River Access Points (Public) | sara2263_thrive_geohub | public
  summary        : 'This layer represents public stream access points within the Thrive R
  description    : "<p><span style='background-color:rgb(255,255,255); color:rgb(20,20,20
  acknowledgments: None
    layer    | River Access Points (Public)               | https://thrive-geohub.maps.arcgis.com/home/item.html?id=f36951b64bac47fdbcce339abbd39085
========================================================================================
ebeb65deb5c14f4d8849fd68944b7ee6 | USA 2020 Census Population Characteristics | esri_demographics | public
  summary        : 'This layer contains the U.S. Census Bureau’s 2020 Census Demographic
  description    : '<div style=\'clear:both; margin:0px; padding:0px;\'><p style=\'font-k
  acknowledgments: 'U.S. Census Bureau, Esri'
    layer    | Block Group                                | https://thrive-geohub.maps.arcgis.com/home/item.html?id=ebeb65deb5c14f4d8849fd68944b7ee6
    sublayer | Block Group                                | https://thrive-geohub.maps.arcgis.com/home/item.html?id=ebeb65deb5c14f4d8849fd68944b7ee6&sublayer=4
    layer    | Census Tract                               | https://thrive-geohub.maps.arcgis.com/home/item.html?id=ebeb65deb5c14f4d8849fd68944b7ee6
    sublayer | Census Tract                               | https://thrive-geohub.maps.arcgis.com/home/item.html?id=ebeb65deb5c14f4d8849fd68944b7ee6&sublayer=3
    layer    | County                                     | https://thrive-geohub.maps.arcgis.com/home/item.html?id=ebeb65deb5c14f4d8849fd68944b7ee6
    sublayer | County                                     | https://thrive-geohub.maps.arcgis.com/home/item.html?id=ebeb65deb5c14f4d8849fd68944b7ee6&sublayer=2
    layer    | State                                      | https://thrive-geohub.maps.arcgis.com/home/item.html?id=ebeb65deb5c14f4d8849fd68944b7ee6
    sublayer | State                                      | https://thrive-geohub.maps.arcgis.com/home/item.html?id=ebeb65deb5c14f4d8849fd68944b7ee6&sublayer=1
    layer    | Nation                                     | https://thrive-geohub.maps.arcgis.com/home/item.html?id=ebeb65deb5c14f4d8849fd68944b7ee6
    sublayer | Nation                                     | https://thrive-geohub.maps.arcgis.com/home/item.html?id=ebeb65deb5c14f4d8849fd68944b7ee6&sublayer=0
========================================================================================

In [6]:
# needs df from the cell above.
# Only what a person edits in the portal. Column names are the portal's own labels.
# item page fields: Title, Summary, Description, Acknowledgments, Sharing
# a layer row and a sublayer row both exist, so the reviewer knows there are two places to look.
item_rows = []

for iid in df['item_id'].dropna().unique():
    item = gis.content.get(iid)
    if item is None:
        continue
    item_rows.append({
        'item_id':         iid,
        'item_title':      item.get('title'),
        'summary':         item.get('snippet'),          # portal label: Summary
        'description':     item.get('description'),      # portal label: Description
        'acknowledgments': item.get('accessInformation'),  # portal label: Acknowledgments
        'owner':           item.get('owner'),
        'sharing':         item.get('access'),           # portal label: Sharing
    })

items = pd.DataFrame(item_rows)
layers = df.drop(columns=['sublayer_name']).merge(items, on='item_id', how='left')

# the page to open in order to edit this row
layers['edit_link'] = gis.url + '/home/item.html?id=' + layers['item_id'].fillna('')
sub_layer = layers['sublayer_id'].notna()
layers.loc[sub_layer, 'edit_link'] = (layers.loc[sub_layer, 'edit_link'] + '&sublayer='
                                      + layers.loc[sub_layer, 'sublayer_id'].astype(int).astype(str))

# which editable fields are still empty on this row
fields = ['summary', 'description', 'acknowledgments']
layers['missing'] = layers[fields].fillna('').apply(
    lambda r: ', '.join(f for f in fields if not str(r[f]).strip()), axis=1)

# what to be careful about on this row
layers['notes'] = ''
layers.loc[sub_layer, 'notes'] = ("values shown are the item text. A sublayer's own summary and "
                                  "description are not readable through the API, check them on this page.")

# the REST url is developer-only, so it is not part of the deliverable
keep = ['map_slug', 'group', 'layer_title', 'level', 'sublayer_id', 'item_id', 'item_title',
        'summary', 'description', 'acknowledgments', 'owner', 'sharing', 'missing', 'notes', 'edit_link']
layers = layers[keep]

print(layers.shape)
print('rows with nothing missing  :', layers.missing.eq('').sum(), 'of', len(layers))
print('rows missing summary       :', layers.missing.str.contains('summary').sum())
print('rows missing description   :', layers.missing.str.contains('description').sum())
print('rows missing acknowledgments:', layers.missing.str.contains('acknowledgments').sum())
print('rows editable by us (owner is the Thrive account):', layers.owner.eq('sara2263_thrive_geohub').sum())
layers

(170, 15)
rows with nothing missing  : 21 of 170
rows missing summary       : 41
rows missing description   : 64
rows missing acknowledgments: 149
rows editable by us (owner is the Thrive account): 73

,map_slug,group,layer_title,level,sublayer_id,item_id,item_title,summary,description,acknowledgments,owner,sharing,missing,notes,edit_link
0,natural-treasures,Cross Sector Data,parcels,layer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"summary, description, acknowledgments",,https://thrive-geohub.maps.arcgis.com/home/ite...
1,natural-treasures,Cross Sector Data,Tax Parcel Boundaries,layer,NaN,a2050b09baff493aa4ad7848ba2fac00,Regrid USA Nationwide Parcel Boundaries,Regrid Nationwide Parcel Boundaries for the Un...,<p style='text-align:center;'><a target='_blan...,Regrid,data_regrid,public,,,https://thrive-geohub.maps.arcgis.com/home/ite...
2,natural-treasures,Cross Sector Data,Population Change 2000-2020,layer,NaN,5239d5d3ea5f4d13a325ad0184377963,Population Change by Tract (2000-2020),NaN,NaN,NaN,sara2263_thrive_geohub,public,"summary, description, acknowledgments",,https://thrive-geohub.maps.arcgis.com/home/ite...
3,natural-treasures,Cross Sector Data,Population Change 2000-2020,sublayer,34.0,5239d5d3ea5f4d13a325ad0184377963,Population Change by Tract (2000-2020),NaN,NaN,NaN,sara2263_thrive_geohub,public,"summary, description, acknowledgments",values shown are the item text. A sublayer's o...,https://thrive-geohub.maps.arcgis.com/home/ite...
4,natural-treasures,Land Use,Developed Land Change,layer,NaN,c8cb5376347542f597437060984d4069,landcover change watershed 1 mile hex grid,Land use change aggregated to 1 mile hex bins ...,NaN,NaN,sara2263_thrive_geohub,public,"description, acknowledgments",,https://thrive-geohub.maps.arcgis.com/home/ite...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,transportation-infrastructure,Thrive boundaries and mask layers,thrive_primary_region_mask,layer,NaN,c8535d9ac4fd485b8a7e88a70dd2cbc7,thrive_primary_region_mask,,,,sara2263_thrive_geohub,public,"summary, description, acknowledgments",,https://thrive-geohub.maps.arcgis.com/home/ite...
166,transportation-infrastructure,Thrive boundaries and mask layers,thrive_primary_region_mask,sublayer,0.0,c8535d9ac4fd485b8a7e88a70dd2cbc7,thrive_primary_region_mask,,,,sara2263_thrive_geohub,public,"summary, description, acknowledgments",values shown are the item text. A sublayer's o...,https://thrive-geohub.maps.arcgis.com/home/ite...
167,transportation-infrastructure,Thrive boundaries and mask layers,thrive_secondary_boundary,layer,NaN,562632e4f4c447ff9f1accd4a7640bb6,thrive_secondary_boundary,,,,sara2263_thrive_geohub,public,"summary, description, acknowledgments",,https://thrive-geohub.maps.arcgis.com/home/ite...
168,transportation-infrastructure,Thrive boundaries and mask layers,thrive_secondary_boundary,sublayer,0.0,562632e4f4c447ff9f1accd4a7640bb6,thrive_secondary_boundary,,,,sara2263_thrive_geohub,public,"summary, description, acknowledgments",values shown are the item text. A sublayer's o...,https://thrive-geohub.maps.arcgis.com/home/ite...
169,transportation-infrastructure,Thrive boundaries and mask layers,Thrive Counties,layer,NaN,f97879f1e2b3463597ad7a0e43248d92,thrive_primary_counties,NaN,NaN,NaN,sara2263_thrive_geohub,public,"summary, description, acknowledgments",,https://thrive-geohub.maps.arcgis.com/home/ite...

In [7]:
layers.to_excel( "../PY/260931_layers_metadata.xlsx" )

## Accessing group layers, layers and sublayers

In [26]:
# one row per node in the web map: group, layer, sublayer
# a group node is a group. an entry that draws a whole service, or the only layer of a
# service, is a layer. an entry that draws one of several layers of one service is a sublayer.
import urllib.request

skip_titles = {'Cross Sector Data', 'Thrive County Boundaries',
               'Thrive watershed region', 'waterbodies'}

nodes = []
service_layers = {}


def service_root(url):
    for suffix in ('/FeatureServer', '/MapServer', '/ImageServer', '/VectorTileServer'):
        if suffix in url:
            return url[:url.index(suffix) + len(suffix)]
    return None


def layer_count(root):
    # layers + tables on the service root, one call per service
    if root not in service_layers:
        try:
            data = json.loads(urllib.request.urlopen(root + '?f=json', timeout=60).read())
            service_layers[root] = len(data.get('layers') or []) + len(data.get('tables') or [])
        except Exception as error:
            print('service root failed:', root, error)
            service_layers[root] = 1
    return service_layers[root]


def read_nodes(items, path, slug, map_title, map_id):
    for n in items:
        node_title = str(n.get('title') or '')
        if node_title in skip_titles:
            continue
        url = n.get('url') or ''
        row = {
            'map_slug': slug,
            'map_title': map_title,
            'map_id': map_id,
            'group_path': ' > '.join(path),
            'node_title': node_title,
            'node_type': n.get('layerType'),
            'item_id': n.get('itemId'),
        }
        if n.get('layerType') == 'GroupLayer':
            nodes.append({**row, 'kind': 'group', 'sublayer_id': None, 'url': url})
            read_nodes(n.get('layers') or [], path + [node_title], slug, map_title, map_id)
            continue
        root = service_root(url)
        tail = url.rstrip('/').split('/')[-1]
        index = int(tail) if (root and tail.isdigit()) else None
        # several layers on the service means this entry draws one of them
        sublayer = root is not None and layer_count(root) > 1
        nodes.append({**row, 'kind': 'sublayer' if sublayer else 'layer',
                      'sublayer_id': index if sublayer else None, 'url': url})


for slug, m in maps.items():
    wm = gis.content.get(m['mapId']).get_data()
    read_nodes(wm.get('operationalLayers', []), [], slug, m['title'], m['mapId'])

nodes = pd.DataFrame(nodes)
print(len(nodes), 'rows |', (nodes.kind == 'group').sum(), 'group |',
      (nodes.kind == 'layer').sum(), 'layer |',
      (nodes.kind == 'sublayer').sum(), 'sublayer |',
      nodes.item_id.nunique(), 'unique items')
nodes

107 rows | 16 group | 54 layer | 37 sublayer | 57 unique items

,map_slug,map_title,map_id,group_path,node_title,node_type,item_id,kind,sublayer_id,url
0,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,,Land Use,GroupLayer,d4f639dd817a435fb4bb68fc6102b9c9,group,NaN,
1,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Land Use,Developed Land Change,ArcGISFeatureLayer,c8cb5376347542f597437060984d4069,layer,NaN,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/...
2,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Land Use,Natural Cover Change,ArcGISFeatureLayer,c8cb5376347542f597437060984d4069,layer,NaN,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/...
3,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Land Use,Land Use Change 2004 – 2024 60 meter resolution,ArcGISTiledImageServiceLayer,d54eeaddbc3e442eae779aacc06fdf7c,layer,NaN,https://tiledimageservices3.arcgis.com/xpR2E2r...
4,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Land Use,Future Land Cover: 2050,ArcGISImageServiceLayer,13c415b776c0463e863f89361ed688da,layer,NaN,https://env1.arcgis.com/arcgis/rest/services/L...
...,...,...,...,...,...,...,...,...,...,...
102,transportation-infrastructure,Transportation + Infrastructure,25c75ac490b94b85b02aa4fd2f341fbb,Thrive boundaries and mask layers,Waterbodies,ArcGISFeatureLayer,3ca7f70273f74d2a89982e5cecee4d98,layer,NaN,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/...
103,transportation-infrastructure,Transportation + Infrastructure,25c75ac490b94b85b02aa4fd2f341fbb,Thrive boundaries and mask layers,thrive_secondary_mask,ArcGISFeatureLayer,28d4e8ba15f542f48d952709a2ab2581,layer,NaN,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/...
104,transportation-infrastructure,Transportation + Infrastructure,25c75ac490b94b85b02aa4fd2f341fbb,Thrive boundaries and mask layers,thrive_primary_region_mask,ArcGISFeatureLayer,c8535d9ac4fd485b8a7e88a70dd2cbc7,layer,NaN,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/...
105,transportation-infrastructure,Transportation + Infrastructure,25c75ac490b94b85b02aa4fd2f341fbb,Thrive boundaries and mask layers,thrive_secondary_boundary,ArcGISFeatureLayer,562632e4f4c447ff9f1accd4a7640bb6,layer,NaN,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/...
106,transportation-infrastructure,Transportation + Infrastructure,25c75ac490b94b85b02aa4fd2f341fbb,Thrive boundaries and mask layers,Thrive Counties,GeoJSON,f97879f1e2b3463597ad7a0e43248d92,layer,NaN,https://www.arcgis.com/sharing/rest/content/it...

In [27]:
# summary and description for each row: the item's own text, and for a sublayer the layer's
# own description when it has one, since every sublayer of a service shares the item text.
import urllib.request

items = {}
for item_id in nodes.item_id.dropna().unique():
    items[item_id] = gis.content.get(item_id)


def layer_description(url):
    if not url:
        return None
    try:
        return json.loads(urllib.request.urlopen(url + '?f=json', timeout=60).read()).get('description')
    except Exception as error:
        print('layer failed:', url, error)
        return None


layer_text = {}
for row in nodes.itertuples():
    if row.kind == 'sublayer' and row.url not in layer_text:
        layer_text[row.url] = layer_description(row.url)


def item_of(row):
    return items.get(row.item_id)


nodes['summary'] = [getattr(item_of(r), 'snippet', None) for r in nodes.itertuples()]
nodes['description'] = [
    (layer_text.get(r.url) if r.kind == 'sublayer' else None)
    or getattr(item_of(r), 'description', None)
    for r in nodes.itertuples()
]

print('summary filled:', nodes.summary.notna().sum(), '| description filled:',
      nodes.description.notna().sum(), '| of', len(nodes), 'rows')
nodes

summary filled: 83 | description filled: 65 | of 107 rows

,map_slug,map_title,map_id,group_path,node_title,node_type,item_id,kind,sublayer_id,url,summary,description
0,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,,Land Use,GroupLayer,d4f639dd817a435fb4bb68fc6102b9c9,group,NaN,,"How is development affecting forests, farmland...",NaN
1,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Land Use,Developed Land Change,ArcGISFeatureLayer,c8cb5376347542f597437060984d4069,layer,NaN,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/...,Land use change aggregated to 1 mile hex bins ...,NaN
2,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Land Use,Natural Cover Change,ArcGISFeatureLayer,c8cb5376347542f597437060984d4069,layer,NaN,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/...,Land use change aggregated to 1 mile hex bins ...,NaN
3,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Land Use,Land Use Change 2004 – 2024 60 meter resolution,ArcGISTiledImageServiceLayer,d54eeaddbc3e442eae779aacc06fdf7c,layer,NaN,https://tiledimageservices3.arcgis.com/xpR2E2r...,,
4,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Land Use,Future Land Cover: 2050,ArcGISImageServiceLayer,13c415b776c0463e863f89361ed688da,layer,NaN,https://env1.arcgis.com/arcgis/rest/services/L...,Land use modeled to represent possible changes...,<p>Predicted land cover for each country for y...
...,...,...,...,...,...,...,...,...,...,...,...,...
102,transportation-infrastructure,Transportation + Infrastructure,25c75ac490b94b85b02aa4fd2f341fbb,Thrive boundaries and mask layers,Waterbodies,ArcGISFeatureLayer,3ca7f70273f74d2a89982e5cecee4d98,layer,NaN,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/...,NaN,NaN
103,transportation-infrastructure,Transportation + Infrastructure,25c75ac490b94b85b02aa4fd2f341fbb,Thrive boundaries and mask layers,thrive_secondary_mask,ArcGISFeatureLayer,28d4e8ba15f542f48d952709a2ab2581,layer,NaN,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/...,NaN,NaN
104,transportation-infrastructure,Transportation + Infrastructure,25c75ac490b94b85b02aa4fd2f341fbb,Thrive boundaries and mask layers,thrive_primary_region_mask,ArcGISFeatureLayer,c8535d9ac4fd485b8a7e88a70dd2cbc7,layer,NaN,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/...,,
105,transportation-infrastructure,Transportation + Infrastructure,25c75ac490b94b85b02aa4fd2f341fbb,Thrive boundaries and mask layers,thrive_secondary_boundary,ArcGISFeatureLayer,562632e4f4c447ff9f1accd4a7640bb6,layer,NaN,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/...,,
106,transportation-infrastructure,Transportation + Infrastructure,25c75ac490b94b85b02aa4fd2f341fbb,Thrive boundaries and mask layers,Thrive Counties,GeoJSON,f97879f1e2b3463597ad7a0e43248d92,layer,NaN,https://www.arcgis.com/sharing/rest/content/it...,NaN,NaN

In [28]:
nodes.to_excel( "../PY/260931_nodelist_wDesc.xlsx" )