# pulling metadata information from maps layer and its sublayers.

In [1]:
from arcgis.gis import GIS
import pandas as pd
from dotenv import load_dotenv
import os
import json

load_dotenv()


signin_name = os.getenv('ESRI_USERNAME')
signin_password = os.getenv('ESRI_PASSWORD')
signin_link = os.getenv("HUBLINK")

# Connect to the organization
gis = GIS(signin_link, signin_name, signin_password )
username = gis.users.me.username

print("Done")

Done

In [2]:
maps = {
	'natural-treasures': {
		'title': 'Natural Treasures',
		'mapId': 'aba702c5420e4a36ac645f14a00ba8f1'
	},
	'transportation-infrastructure': {
		'title': 'Transportation + Infrastructure',
		'mapId': '25c75ac490b94b85b02aa4fd2f341fbb'
	}
}

## Find layer metadata - nested

In [28]:
skip_titles = {'Cross Sector Data', 'Thrive County Boundaries',
               'Thrive watershed region', 'waterbodies'}

rows = []

for slug, m in maps.items():
    map_item = gis.content.get(m['mapId'])
    wm = map_item.get_data()
    for top in wm.get('operationalLayers', []):
        top_title = str(top.get('title'))
        if top_title in skip_titles:
            continue
        is_group = top.get('layerType') == 'GroupLayer'
        if is_group and not top.get('layers'):
            continue
        group = top_title if is_group else ''
        for lyr in (top.get('layers') or []) if is_group else [top]:
            layer_title = str(lyr.get('title'))
            if layer_title in skip_titles:
                continue
            url = lyr.get('url') or ''
            # one row per map entry, plus one row for the service layer that entry draws.
            # the entry url ends in that layer's index, so no item.layers call is needed here
            # and nothing gets repeated under the wrong parent. image services have no index.
            tail = url.rstrip('/').split('/')[-1]
            base = {
                'map_slug': slug,
                'map_title': m['title'],
                'map_id': m['mapId'],
                'group': group,
                'layer_title': layer_title,
                'layer_type': lyr.get('layerType'),
                'item_id': lyr.get('itemId'),
                'url': url,
            }
            rows.append({**base, 'level': 'layer',
                         'sublayer_id': None, 'sublayer_name': None})
            if tail.isdigit():
                rows.append({**base, 'level': 'sublayer',
                             'sublayer_id': int(tail), 'sublayer_name': None})
    break

df = pd.DataFrame(rows)
print(len(df), 'rows |', (df.level == 'layer').sum(), 'layer |', (df.level == 'sublayer').sum(), 'sublayer |',
      df.item_id.nunique(), 'unique items |',
      df[['item_id', 'sublayer_id']].dropna().drop_duplicates().shape[0], 'unique item+sublayer pairs')
df

38 rows | 21 layer | 17 sublayer | 19 unique items | 15 unique item+sublayer pairs

,map_slug,map_title,map_id,group,layer_title,layer_type,item_id,url,level,sublayer_id,sublayer_name
0,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Land Use Change,"Developed Land Change 2004–2024, Percent Per Mile",ArcGISFeatureLayer,c8cb5376347542f597437060984d4069,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/arcgis/res...,layer,NaN,None
1,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Land Use Change,"Developed Land Change 2004–2024, Percent Per Mile",ArcGISFeatureLayer,c8cb5376347542f597437060984d4069,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/arcgis/res...,sublayer,0.0,None
2,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Land Use Change,Natural Cover Change 2004–2024 percent mile,ArcGISFeatureLayer,c8cb5376347542f597437060984d4069,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/arcgis/res...,layer,NaN,None
3,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Land Use Change,Natural Cover Change 2004–2024 percent mile,ArcGISFeatureLayer,c8cb5376347542f597437060984d4069,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/arcgis/res...,sublayer,0.0,None
4,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Land Use Change,Land Use Change 2004 – 2024 60 meter resolution,ArcGISTiledImageServiceLayer,d54eeaddbc3e442eae779aacc06fdf7c,https://tiledimageservices3.arcgis.com/xpR2E2r2KmCE5hF3/...,layer,NaN,None
5,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Land Use Change,Future Land Cover: 2050,ArcGISImageServiceLayer,13c415b776c0463e863f89361ed688da,https://env1.arcgis.com/arcgis/rest/services/Land_Cover_...,layer,NaN,None
6,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Land Use Change,thrive_watershed_huc10_boundary,ArcGISFeatureLayer,49f5a7a36df7476fb13a1daec41f8714,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/arcgis/res...,layer,NaN,None
7,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Land Use Change,thrive_watershed_huc10_boundary,ArcGISFeatureLayer,49f5a7a36df7476fb13a1daec41f8714,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/arcgis/res...,sublayer,0.0,None
8,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Agriculture & Working Lands,"Agricultural Land Change, Percent Per Mile",ArcGISFeatureLayer,c8cb5376347542f597437060984d4069,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/arcgis/res...,layer,NaN,None
9,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Agriculture & Working Lands,"Agricultural Land Change, Percent Per Mile",ArcGISFeatureLayer,c8cb5376347542f597437060984d4069,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/arcgis/res...,sublayer,0.0,None
10,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Agriculture & Working Lands,Agricultural Suitability,ArcGISTiledImageServiceLayer,7832080ff813443db6156aa7d6c905c8,https://tiledimageservices.arcgis.com/UnTXoPXBYERF0OH6/a...,layer,NaN,None
11,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Biodiversity & Habitat,Invasive Species Observations,ArcGISFeatureLayer,90500e937941425abb5f91f8c727f72a,https://services.arcgis.com/UnTXoPXBYERF0OH6/arcgis/rest...,layer,NaN,None
12,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Biodiversity & Habitat,Invasive Species Observations,ArcGISFeatureLayer,90500e937941425abb5f91f8c727f72a,https://services.arcgis.com/UnTXoPXBYERF0OH6/arcgis/rest...,sublayer,0.0,None
13,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Biodiversity & Habitat,Threatened Species,ArcGISFeatureLayer,2409942bd2b143059b4b15bc018bce4a,https://services.arcgis.com/UnTXoPXBYERF0OH6/arcgis/rest...,layer,NaN,None
14,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Biodiversity & Habitat,Threatened Species,ArcGISFeatureLayer,2409942bd2b143059b4b15bc018bce4a,https://services.arcgis.com/UnTXoPXBYERF0OH6/arcgis/rest...,sublayer,0.0,None
15,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Biodiversity & Habitat,Intact Habitat Cores,ArcGISTiledImageServiceLayer,e0ec4650fa8f4f59a016baf36937125e,https://tiledimageservices.arcgis.com/UnTXoPXBYERF0OH6/a...,layer,NaN,None
16,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Protected Lands,Protected Lands (2026),ArcGISFeatureLayer,0edfcf9c2014474fab8a9d5bab2c9084,https://services.arcgis.com/UnTXoPXBYERF0OH6/arcgis/rest...,layer,NaN,None
17,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Protected Lands,Protected Lands (2026),ArcGISFeatureLayer,0edfcf9c2014474fab8a9d5bab2c9084,https://services.arcgis.com/UnTXoPXBYERF0OH6/arcgis/rest...,sublayer,0.0,None
18,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Protected Lands,Protected Farmland,ArcGISFeatureLayer,c6c00112223c4412a93fed76a8086ef9,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/arcgis/res...,layer,NaN,None
19,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Protected Lands,Protected Farmland,ArcGISFeatureLayer,c6c00112223c4412a93fed76a8086ef9,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/arcgis/res...,sublayer,0.0,None
20,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Protected Lands,Conservation Priority Areas,ArcGISFeatureLayer,abd42c2259f04ae886d83cfe3f8bdfc7,https://services.arcgis.com/UnTXoPXBYERF0OH6/arcgis/rest...,layer,NaN,None
21,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Protected Lands,Conservation Priority Areas,ArcGISFeatureLayer,abd42c2259f04ae886d83cfe3f8bdfc7,https://services.arcgis.com/UnTXoPXBYERF0OH6/arcgis/rest...,sublayer,0.0,None
22,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Water Resources,Stream health,ArcGISFeatureLayer,7329aefb41374f19b288158261969e56,https://services.arcgis.com/UnTXoPXBYERF0OH6/arcgis/rest...,layer,NaN,None
23,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Water Resources,Stream health,ArcGISFeatureLayer,7329aefb41374f19b288158261969e56,https://services.arcgis.com/UnTXoPXBYERF0OH6/arcgis/rest...,sublayer,0.0,None
24,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Water Resources,Waterbody health,ArcGISFeatureLayer,78fec49ff3e4442dbe265a1c2be605e1,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/arcgis/res...,layer,NaN,None
25,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Water Resources,Waterbody health,ArcGISFeatureLayer,78fec49ff3e4442dbe265a1c2be605e1,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/arcgis/res...,sublayer,0.0,None
26,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Water Resources,Brownfield Sites,ArcGISFeatureLayer,5197c7e3bc0b4810a4afa8b62020c357,https://services.arcgis.com/cJ9YHowT8TU7DUyn/arcgis/rest...,layer,NaN,None
27,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Water Resources,Brownfield Sites,ArcGISFeatureLayer,5197c7e3bc0b4810a4afa8b62020c357,https://services.arcgis.com/cJ9YHowT8TU7DUyn/arcgis/rest...,sublayer,0.0,None
28,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Water Resources,Superfund sites,ArcGISFeatureLayer,8d81d6bdada5418c95365b0dabea2747,https://services.arcgis.com/cJ9YHowT8TU7DUyn/arcgis/rest...,layer,NaN,None
29,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Water Resources,Superfund sites,ArcGISFeatureLayer,8d81d6bdada5418c95365b0dabea2747,https://services.arcgis.com/cJ9YHowT8TU7DUyn/arcgis/rest...,sublayer,0.0,None
30,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Outdoor Recreation,Parks,ArcGISFeatureLayer,e243bedec65443a0aba929442af1ecb8,https://services.arcgis.com/UnTXoPXBYERF0OH6/arcgis/rest...,layer,NaN,None
31,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Outdoor Recreation,Parks,ArcGISFeatureLayer,e243bedec65443a0aba929442af1ecb8,https://services.arcgis.com/UnTXoPXBYERF0OH6/arcgis/rest...,sublayer,0.0,None
32,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Outdoor Recreation,Parks and nature reserves,ArcGISFeatureLayer,09e74021fc5749a181e783a111905767,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/arcgis/res...,layer,NaN,None
33,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Outdoor Recreation,Parks and nature reserves,ArcGISFeatureLayer,09e74021fc5749a181e783a111905767,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/arcgis/res...,sublayer,0.0,None
34,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Outdoor Recreation,Hiking Trails,ArcGISFeatureLayer,18cacd1713e245b9916b53b7ef52f416,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/arcgis/res...,layer,NaN,None
35,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Outdoor Recreation,Hiking Trails,ArcGISFeatureLayer,18cacd1713e245b9916b53b7ef52f416,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/arcgis/res...,sublayer,0.0,None
36,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Outdoor Recreation,River Access,ArcGISFeatureLayer,48621d7af80e4b6cbcacf17afbfc6507,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/arcgis/res...,layer,NaN,None
37,natural-treasures,Natural Treasures,aba702c5420e4a36ac645f14a00ba8f1,Outdoor Recreation,River Access,ArcGISFeatureLayer,48621d7af80e4b6cbcacf17afbfc6507,https://services3.arcgis.com/xpR2E2r2KmCE5hF3/arcgis/res...,sublayer,0.0,None

In [29]:
# test every item in the list: its text, and the rows that carry it
for iid in df['item_id'].dropna().unique():
    item = gis.content.get(iid)
    print('=' * 88)
    if item is None:
        print(iid, '-> the item did not come back')
        continue
    print(iid, '|', item.get('title'), '|', item.get('owner'), '|', item.get('access'))
    print('  summary        :', repr(item.get('snippet'))[:70])
    print('  description    :', repr(item.get('description'))[:70])
    print('  acknowledgments:', repr(item.get('accessInformation'))[:70])
    for r in df[df.item_id == iid].itertuples():
        if pd.isna(r.sublayer_id):
            link = f"{gis.url}/home/item.html?id={iid}"
        else:
            link = f"{gis.url}/home/item.html?id={iid}&sublayer={int(r.sublayer_id)}"
        print(f'    {r.level:8s} | {str(r.layer_title)[:42]:42s} | {link}')

========================================================================================
c8cb5376347542f597437060984d4069 | hex_grid_1mi_landcover_change_watershed | sara2263_thrive_geohub | public
  summary        : None
  description    : None
  acknowledgments: None
    layer    | Developed Land Change 2004–2024, Percent P | https://thrive-geohub.maps.arcgis.com/home/item.html?id=c8cb5376347542f597437060984d4069
    sublayer | Developed Land Change 2004–2024, Percent P | https://thrive-geohub.maps.arcgis.com/home/item.html?id=c8cb5376347542f597437060984d4069&sublayer=0
    layer    | Natural Cover Change 2004–2024 percent mil | https://thrive-geohub.maps.arcgis.com/home/item.html?id=c8cb5376347542f597437060984d4069
    sublayer | Natural Cover Change 2004–2024 percent mil | https://thrive-geohub.maps.arcgis.com/home/item.html?id=c8cb5376347542f597437060984d4069&sublayer=0
    layer    | Agricultural Land Change, Percent Per Mile | https://thrive-geohub.maps.arcgis.com/home/item.html?id=c8cb5376347542f597437060984d4069
    sublayer | Agricultural Land Change, Percent Per Mile | https://thrive-geohub.maps.arcgis.com/home/item.html?id=c8cb5376347542f597437060984d4069&sublayer=0
========================================================================================
d54eeaddbc3e442eae779aacc06fdf7c | landuse_change_watershed_boundary_2004_2024_60m | sara2263_thrive_geohub | public
  summary        : ''
  description    : ''
  acknowledgments: ''
    layer    | Land Use Change 2004 – 2024 60 meter resol | https://thrive-geohub.maps.arcgis.com/home/item.html?id=d54eeaddbc3e442eae779aacc06fdf7c
========================================================================================
13c415b776c0463e863f89361ed688da | Land Cover 2050 - Country | sara2263_thrive_geohub | public
  summary        : 'Predicted land cover for each country for year 2050, generated by Cla
  description    : None
  acknowledgments: None
    layer    | Future Land Cover: 2050                    | https://thrive-geohub.maps.arcgis.com/home/item.html?id=13c415b776c0463e863f89361ed688da
========================================================================================
49f5a7a36df7476fb13a1daec41f8714 | thrive_watershed_huc10_boundary | sara2263_thrive_geohub | public
  summary        : None
  description    : None
  acknowledgments: None
    layer    | thrive_watershed_huc10_boundary            | https://thrive-geohub.maps.arcgis.com/home/item.html?id=49f5a7a36df7476fb13a1daec41f8714
    sublayer | thrive_watershed_huc10_boundary            | https://thrive-geohub.maps.arcgis.com/home/item.html?id=49f5a7a36df7476fb13a1daec41f8714&sublayer=0
========================================================================================
7832080ff813443db6156aa7d6c905c8 | Thrive Agricultural Suitability Model 2026 | vqq585_mymocs | public
  summary        : 'This version of the 2026 Thrive Agricultural Suitability Model has ha
  description    : '<p>This version of the 2026 Thrive Agricultural Suitability Model has
  acknowledgments: None
    layer    | Agricultural Suitability                   | https://thrive-geohub.maps.arcgis.com/home/item.html?id=7832080ff813443db6156aa7d6c905c8
========================================================================================
90500e937941425abb5f91f8c727f72a | Cradle Region Invasive Species Observations (Watershed Boundary) | GZG367_IGTLab | public
  summary        : 'Consolidated invasive species observation records for the Thrive regi
  description    : "<p><strong>Overview</strong></p><p style='background-color:rgb(255, 2
  acknowledgments: 'EDDMapS'
    layer    | Invasive Species Observations              | https://thrive-geohub.maps.arcgis.com/home/item.html?id=90500e937941425abb5f91f8c727f72a
    sublayer | Invasive Species Observations              | https://thrive-geohub.maps.arcgis.com/home/item.html?id=90500e937941425abb5f91f8c727f72a&sublayer=0
========================================================================================
2409942bd2b143059b4b15bc018bce4a | Thrive Cradle Imperiled Species Zonal Statistics | vqq585_mymocs | public
  summary        : 'Hexagon-based zonal statistics summarizing imperiled species richness
  description    : "<p><strong>Overview</strong></p><p>This feature service provides hexa
  acknowledgments: ''
    layer    | Threatened Species                         | https://thrive-geohub.maps.arcgis.com/home/item.html?id=2409942bd2b143059b4b15bc018bce4a
    sublayer | Threatened Species                         | https://thrive-geohub.maps.arcgis.com/home/item.html?id=2409942bd2b143059b4b15bc018bce4a&sublayer=0
========================================================================================
e0ec4650fa8f4f59a016baf36937125e | Thrive Cradle Habitat Cores 2026 | vqq585_mymocs | public
  summary        : 'Thematic raster of modeled intact habitat cores for the Thrive Cradle
  description    : "<p><strong>Overview</strong></p><p>This Image Service provides a them
  acknowledgments: "Esri's Green Infrastructure Initiative"
    layer    | Intact Habitat Cores                       | https://thrive-geohub.maps.arcgis.com/home/item.html?id=e0ec4650fa8f4f59a016baf36937125e
========================================================================================
0edfcf9c2014474fab8a9d5bab2c9084 | Protected Lands in the Cradle of Southern Appalachia (2026) | vqq585_mymocs | public
  summary        : 'This service delivers detailed spatial data on protected lands in the
  description    : "<p><strong>Overview</strong></p><p>This feature service provides deta
  acknowledgments: ''
    layer    | Protected Lands (2026)                     | https://thrive-geohub.maps.arcgis.com/home/item.html?id=0edfcf9c2014474fab8a9d5bab2c9084
    sublayer | Protected Lands (2026)                     | https://thrive-geohub.maps.arcgis.com/home/item.html?id=0edfcf9c2014474fab8a9d5bab2c9084&sublayer=0
========================================================================================
c6c00112223c4412a93fed76a8086ef9 | PALD_thrive_region_farmland_trust_2025 | sara2263_thrive_geohub | public
  summary        : None
  description    : None
  acknowledgments: None
    layer    | Protected Farmland                         | https://thrive-geohub.maps.arcgis.com/home/item.html?id=c6c00112223c4412a93fed76a8086ef9
    sublayer | Protected Farmland                         | https://thrive-geohub.maps.arcgis.com/home/item.html?id=c6c00112223c4412a93fed76a8086ef9&sublayer=0
========================================================================================
abd42c2259f04ae886d83cfe3f8bdfc7 | Landscape Conservation Priority Model | cmix0085 | public
  summary        : "This map ranks the landscape based on intact habitat cores, corridors
  description    : "<p>This map ranks the landscape based on intact habitat cores, corrid
  acknowledgments: ''
    layer    | Conservation Priority Areas                | https://thrive-geohub.maps.arcgis.com/home/item.html?id=abd42c2259f04ae886d83cfe3f8bdfc7
    sublayer | Conservation Priority Areas                | https://thrive-geohub.maps.arcgis.com/home/item.html?id=abd42c2259f04ae886d83cfe3f8bdfc7&sublayer=0
========================================================================================
7329aefb41374f19b288158261969e56 | Thrive Region 303d Stream Segments (2025) | vqq585_mymocs | public
  summary        : 'USA Impaired or Threatened Waterbodies (303d) stream segments for the
  description    : '<p>This dataset reflects the Thrive Cradle regions 303d listed stream
  acknowledgments: ''
    layer    | Stream health                              | https://thrive-geohub.maps.arcgis.com/home/item.html?id=7329aefb41374f19b288158261969e56
    sublayer | Stream health                              | https://thrive-geohub.maps.arcgis.com/home/item.html?id=7329aefb41374f19b288158261969e56&sublayer=0
========================================================================================
78fec49ff3e4442dbe265a1c2be605e1 | threatened_waterbodies_area_ATTAINS_cipped_thrive_watersheds | sara2263_thrive_geohub | public
  summary        : 'ATTAINs data clipped locally and uploaded. '
  description    : None
  acknowledgments: None
    layer    | Waterbody health                           | https://thrive-geohub.maps.arcgis.com/home/item.html?id=78fec49ff3e4442dbe265a1c2be605e1
    sublayer | Waterbody health                           | https://thrive-geohub.maps.arcgis.com/home/item.html?id=78fec49ff3e4442dbe265a1c2be605e1&sublayer=0
========================================================================================
5197c7e3bc0b4810a4afa8b62020c357 | FRS_INTERESTS_ACRES | sara2263_thrive_geohub | public
  summary        : 'Brownfield sites are identified by the EPA Facility Registry Service
  description    : None
  acknowledgments: None
    layer    | Brownfield Sites                           | https://thrive-geohub.maps.arcgis.com/home/item.html?id=5197c7e3bc0b4810a4afa8b62020c357
    sublayer | Brownfield Sites                           | https://thrive-geohub.maps.arcgis.com/home/item.html?id=5197c7e3bc0b4810a4afa8b62020c357&sublayer=0
========================================================================================
8d81d6bdada5418c95365b0dabea2747 | FRS_INTERESTS_SEMS | sara2263_thrive_geohub | public
  summary        : "EPA's SEMS dataset, copied from URL.\nEPA's Facility Registry Service
  description    : 'SEMS'
  acknowledgments: None
    layer    | Superfund sites                            | https://thrive-geohub.maps.arcgis.com/home/item.html?id=8d81d6bdada5418c95365b0dabea2747
    sublayer | Superfund sites                            | https://thrive-geohub.maps.arcgis.com/home/item.html?id=8d81d6bdada5418c95365b0dabea2747&sublayer=0
========================================================================================
e243bedec65443a0aba929442af1ecb8 | USA_Parks_Thrive_Region2026 | NHunt73 | public
  summary        : 'U.S. Parks represents parks, gardens, and forests within the United S
  description    : 'U.S. Parks provides thousands of parks, gardens, and forests within t
  acknowledgments: 'Esri; TomTom North America, Inc.'
    layer    | Parks                                      | https://thrive-geohub.maps.arcgis.com/home/item.html?id=e243bedec65443a0aba929442af1ecb8
    sublayer | Parks                                      | https://thrive-geohub.maps.arcgis.com/home/item.html?id=e243bedec65443a0aba929442af1ecb8&sublayer=0
========================================================================================
09e74021fc5749a181e783a111905767 | parks_nature_reserves_OSM_20260913 | sara2263_thrive_geohub | public
  summary        : 'Parks and nature reserves from Open Street Maps, Thrive greater regio
  description    : None
  acknowledgments: None
    layer    | Parks and nature reserves                  | https://thrive-geohub.maps.arcgis.com/home/item.html?id=09e74021fc5749a181e783a111905767
    sublayer | Parks and nature reserves                  | https://thrive-geohub.maps.arcgis.com/home/item.html?id=09e74021fc5749a181e783a111905767&sublayer=0
========================================================================================
18cacd1713e245b9916b53b7ef52f416 | trails_county_name_added | sara2263_thrive_geohub | public
  summary        : None
  description    : None
  acknowledgments: None
    layer    | Hiking Trails                              | https://thrive-geohub.maps.arcgis.com/home/item.html?id=18cacd1713e245b9916b53b7ef52f416
    sublayer | Hiking Trails                              | https://thrive-geohub.maps.arcgis.com/home/item.html?id=18cacd1713e245b9916b53b7ef52f416&sublayer=0
========================================================================================
48621d7af80e4b6cbcacf17afbfc6507 | river_access_points_20260913 | sara2263_thrive_geohub | public
  summary        : "A merged copy of UTC's Tennessee River Access Locations and River Acc
  description    : None
  acknowledgments: None
    layer    | River Access                               | https://thrive-geohub.maps.arcgis.com/home/item.html?id=48621d7af80e4b6cbcacf17afbfc6507
    sublayer | River Access                               | https://thrive-geohub.maps.arcgis.com/home/item.html?id=48621d7af80e4b6cbcacf17afbfc6507&sublayer=0

In [30]:
# needs df from the cell above.
# Only what a person edits in the portal. Column names are the portal's own labels.
# item page fields: Title, Summary, Description, Acknowledgments, Sharing
# a layer row and a sublayer row both exist, so the reviewer knows there are two places to look.
item_rows = []

for iid in df['item_id'].dropna().unique():
    item = gis.content.get(iid)
    if item is None:
        continue
    item_rows.append({
        'item_id':         iid,
        'item_title':      item.get('title'),
        'summary':         item.get('snippet'),          # portal label: Summary
        'description':     item.get('description'),      # portal label: Description
        'acknowledgments': item.get('accessInformation'),  # portal label: Acknowledgments
        'owner':           item.get('owner'),
        'sharing':         item.get('access'),           # portal label: Sharing
    })

items = pd.DataFrame(item_rows)
layers = df.drop(columns=['sublayer_name']).merge(items, on='item_id', how='left')

# the page to open in order to edit this row
layers['edit_link'] = gis.url + '/home/item.html?id=' + layers['item_id'].fillna('')
sub_layer = layers['sublayer_id'].notna()
layers.loc[sub_layer, 'edit_link'] = (layers.loc[sub_layer, 'edit_link'] + '&sublayer='
                                      + layers.loc[sub_layer, 'sublayer_id'].astype(int).astype(str))

# which editable fields are still empty on this row
fields = ['summary', 'description', 'acknowledgments']
layers['missing'] = layers[fields].fillna('').apply(
    lambda r: ', '.join(f for f in fields if not str(r[f]).strip()), axis=1)

# what to be careful about on this row
layers['notes'] = ''
layers.loc[sub_layer, 'notes'] = ("values shown are the item text. A sublayer's own summary and "
                                  "description are not readable through the API, check them on this page.")

# the REST url is developer-only, so it is not part of the deliverable
keep = ['map_slug', 'group', 'layer_title', 'level', 'sublayer_id', 'item_id', 'item_title',
        'summary', 'description', 'acknowledgments', 'owner', 'sharing', 'missing', 'notes', 'edit_link']
layers = layers[keep]

print(layers.shape)
print('rows with nothing missing  :', layers.missing.eq('').sum(), 'of', len(layers))
print('rows missing summary       :', layers.missing.str.contains('summary').sum())
print('rows missing description   :', layers.missing.str.contains('description').sum())
print('rows missing acknowledgments:', layers.missing.str.contains('acknowledgments').sum())
print('rows editable by us (owner is the Thrive account):', layers.owner.eq('sara2263_thrive_geohub').sum())
layers

(38, 15)
rows with nothing missing  : 5 of 38
rows missing summary       : 13
rows missing description   : 22
rows missing acknowledgments: 33
rows editable by us (owner is the Thrive account): 24

,map_slug,group,layer_title,level,sublayer_id,item_id,item_title,summary,description,acknowledgments,owner,sharing,missing,notes,edit_link
0,natural-treasures,Land Use Change,"Developed Land Change 2004–2024, Percent Per Mile",layer,NaN,c8cb5376347542f597437060984d4069,hex_grid_1mi_landcover_change_watershed,NaN,NaN,NaN,sara2263_thrive_geohub,public,"summary, description, acknowledgments",,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
1,natural-treasures,Land Use Change,"Developed Land Change 2004–2024, Percent Per Mile",sublayer,0.0,c8cb5376347542f597437060984d4069,hex_grid_1mi_landcover_change_watershed,NaN,NaN,NaN,sara2263_thrive_geohub,public,"summary, description, acknowledgments",values shown are the item text. A sublayer's own summary...,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
2,natural-treasures,Land Use Change,Natural Cover Change 2004–2024 percent mile,layer,NaN,c8cb5376347542f597437060984d4069,hex_grid_1mi_landcover_change_watershed,NaN,NaN,NaN,sara2263_thrive_geohub,public,"summary, description, acknowledgments",,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
3,natural-treasures,Land Use Change,Natural Cover Change 2004–2024 percent mile,sublayer,0.0,c8cb5376347542f597437060984d4069,hex_grid_1mi_landcover_change_watershed,NaN,NaN,NaN,sara2263_thrive_geohub,public,"summary, description, acknowledgments",values shown are the item text. A sublayer's own summary...,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
4,natural-treasures,Land Use Change,Land Use Change 2004 – 2024 60 meter resolution,layer,NaN,d54eeaddbc3e442eae779aacc06fdf7c,landuse_change_watershed_boundary_2004_2024_60m,,,,sara2263_thrive_geohub,public,"summary, description, acknowledgments",,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
5,natural-treasures,Land Use Change,Future Land Cover: 2050,layer,NaN,13c415b776c0463e863f89361ed688da,Land Cover 2050 - Country,"Predicted land cover for each country for year 2050, gen...",NaN,NaN,sara2263_thrive_geohub,public,"description, acknowledgments",,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
6,natural-treasures,Land Use Change,thrive_watershed_huc10_boundary,layer,NaN,49f5a7a36df7476fb13a1daec41f8714,thrive_watershed_huc10_boundary,NaN,NaN,NaN,sara2263_thrive_geohub,public,"summary, description, acknowledgments",,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
7,natural-treasures,Land Use Change,thrive_watershed_huc10_boundary,sublayer,0.0,49f5a7a36df7476fb13a1daec41f8714,thrive_watershed_huc10_boundary,NaN,NaN,NaN,sara2263_thrive_geohub,public,"summary, description, acknowledgments",values shown are the item text. A sublayer's own summary...,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
8,natural-treasures,Agriculture & Working Lands,"Agricultural Land Change, Percent Per Mile",layer,NaN,c8cb5376347542f597437060984d4069,hex_grid_1mi_landcover_change_watershed,NaN,NaN,NaN,sara2263_thrive_geohub,public,"summary, description, acknowledgments",,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
9,natural-treasures,Agriculture & Working Lands,"Agricultural Land Change, Percent Per Mile",sublayer,0.0,c8cb5376347542f597437060984d4069,hex_grid_1mi_landcover_change_watershed,NaN,NaN,NaN,sara2263_thrive_geohub,public,"summary, description, acknowledgments",values shown are the item text. A sublayer's own summary...,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
10,natural-treasures,Agriculture & Working Lands,Agricultural Suitability,layer,NaN,7832080ff813443db6156aa7d6c905c8,Thrive Agricultural Suitability Model 2026,This version of the 2026 Thrive Agricultural Suitability...,<p>This version of the 2026 Thrive Agricultural Suitabil...,NaN,vqq585_mymocs,public,acknowledgments,,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
11,natural-treasures,Biodiversity & Habitat,Invasive Species Observations,layer,NaN,90500e937941425abb5f91f8c727f72a,Cradle Region Invasive Species Observations (Watershed B...,Consolidated invasive species observation records for th...,<p><strong>Overview</strong></p><p style='background-col...,EDDMapS,GZG367_IGTLab,public,,,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
12,natural-treasures,Biodiversity & Habitat,Invasive Species Observations,sublayer,0.0,90500e937941425abb5f91f8c727f72a,Cradle Region Invasive Species Observations (Watershed B...,Consolidated invasive species observation records for th...,<p><strong>Overview</strong></p><p style='background-col...,EDDMapS,GZG367_IGTLab,public,,values shown are the item text. A sublayer's own summary...,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
13,natural-treasures,Biodiversity & Habitat,Threatened Species,layer,NaN,2409942bd2b143059b4b15bc018bce4a,Thrive Cradle Imperiled Species Zonal Statistics,Hexagon-based zonal statistics summarizing imperiled spe...,<p><strong>Overview</strong></p><p>This feature service ...,,vqq585_mymocs,public,acknowledgments,,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
14,natural-treasures,Biodiversity & Habitat,Threatened Species,sublayer,0.0,2409942bd2b143059b4b15bc018bce4a,Thrive Cradle Imperiled Species Zonal Statistics,Hexagon-based zonal statistics summarizing imperiled spe...,<p><strong>Overview</strong></p><p>This feature service ...,,vqq585_mymocs,public,acknowledgments,values shown are the item text. A sublayer's own summary...,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
15,natural-treasures,Biodiversity & Habitat,Intact Habitat Cores,layer,NaN,e0ec4650fa8f4f59a016baf36937125e,Thrive Cradle Habitat Cores 2026,Thematic raster of modeled intact habitat cores for the ...,<p><strong>Overview</strong></p><p>This Image Service pr...,Esri's Green Infrastructure Initiative,vqq585_mymocs,public,,,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
16,natural-treasures,Protected Lands,Protected Lands (2026),layer,NaN,0edfcf9c2014474fab8a9d5bab2c9084,Protected Lands in the Cradle of Southern Appalachia (2026),This service delivers detailed spatial data on protected...,<p><strong>Overview</strong></p><p>This feature service ...,,vqq585_mymocs,public,acknowledgments,,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
17,natural-treasures,Protected Lands,Protected Lands (2026),sublayer,0.0,0edfcf9c2014474fab8a9d5bab2c9084,Protected Lands in the Cradle of Southern Appalachia (2026),This service delivers detailed spatial data on protected...,<p><strong>Overview</strong></p><p>This feature service ...,,vqq585_mymocs,public,acknowledgments,values shown are the item text. A sublayer's own summary...,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
18,natural-treasures,Protected Lands,Protected Farmland,layer,NaN,c6c00112223c4412a93fed76a8086ef9,PALD_thrive_region_farmland_trust_2025,NaN,NaN,NaN,sara2263_thrive_geohub,public,"summary, description, acknowledgments",,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
19,natural-treasures,Protected Lands,Protected Farmland,sublayer,0.0,c6c00112223c4412a93fed76a8086ef9,PALD_thrive_region_farmland_trust_2025,NaN,NaN,NaN,sara2263_thrive_geohub,public,"summary, description, acknowledgments",values shown are the item text. A sublayer's own summary...,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
20,natural-treasures,Protected Lands,Conservation Priority Areas,layer,NaN,abd42c2259f04ae886d83cfe3f8bdfc7,Landscape Conservation Priority Model,This map ranks the landscape based on intact habitat cor...,<p>This map ranks the landscape based on intact habitat ...,,cmix0085,public,acknowledgments,,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
21,natural-treasures,Protected Lands,Conservation Priority Areas,sublayer,0.0,abd42c2259f04ae886d83cfe3f8bdfc7,Landscape Conservation Priority Model,This map ranks the landscape based on intact habitat cor...,<p>This map ranks the landscape based on intact habitat ...,,cmix0085,public,acknowledgments,values shown are the item text. A sublayer's own summary...,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
22,natural-treasures,Water Resources,Stream health,layer,NaN,7329aefb41374f19b288158261969e56,Thrive Region 303d Stream Segments (2025),USA Impaired or Threatened Waterbodies (303d) stream seg...,<p>This dataset reflects the Thrive Cradle regions 303d ...,,vqq585_mymocs,public,acknowledgments,,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
23,natural-treasures,Water Resources,Stream health,sublayer,0.0,7329aefb41374f19b288158261969e56,Thrive Region 303d Stream Segments (2025),USA Impaired or Threatened Waterbodies (303d) stream seg...,<p>This dataset reflects the Thrive Cradle regions 303d ...,,vqq585_mymocs,public,acknowledgments,values shown are the item text. A sublayer's own summary...,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
24,natural-treasures,Water Resources,Waterbody health,layer,NaN,78fec49ff3e4442dbe265a1c2be605e1,threatened_waterbodies_area_ATTAINS_cipped_thrive_waters...,ATTAINs data clipped locally and uploaded.,NaN,NaN,sara2263_thrive_geohub,public,"description, acknowledgments",,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
25,natural-treasures,Water Resources,Waterbody health,sublayer,0.0,78fec49ff3e4442dbe265a1c2be605e1,threatened_waterbodies_area_ATTAINS_cipped_thrive_waters...,ATTAINs data clipped locally and uploaded.,NaN,NaN,sara2263_thrive_geohub,public,"description, acknowledgments",values shown are the item text. A sublayer's own summary...,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
26,natural-treasures,Water Resources,Brownfield Sites,layer,NaN,5197c7e3bc0b4810a4afa8b62020c357,FRS_INTERESTS_ACRES,Brownfield sites are identified by the EPA Facility Regi...,NaN,NaN,sara2263_thrive_geohub,public,"description, acknowledgments",,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
27,natural-treasures,Water Resources,Brownfield Sites,sublayer,0.0,5197c7e3bc0b4810a4afa8b62020c357,FRS_INTERESTS_ACRES,Brownfield sites are identified by the EPA Facility Regi...,NaN,NaN,sara2263_thrive_geohub,public,"description, acknowledgments",values shown are the item text. A sublayer's own summary...,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
28,natural-treasures,Water Resources,Superfund sites,layer,NaN,8d81d6bdada5418c95365b0dabea2747,FRS_INTERESTS_SEMS,"EPA's SEMS dataset, copied from URL.\nEPA's Facility Reg...",SEMS,NaN,sara2263_thrive_geohub,public,acknowledgments,,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
29,natural-treasures,Water Resources,Superfund sites,sublayer,0.0,8d81d6bdada5418c95365b0dabea2747,FRS_INTERESTS_SEMS,"EPA's SEMS dataset, copied from URL.\nEPA's Facility Reg...",SEMS,NaN,sara2263_thrive_geohub,public,acknowledgments,values shown are the item text. A sublayer's own summary...,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
30,natural-treasures,Outdoor Recreation,Parks,layer,NaN,e243bedec65443a0aba929442af1ecb8,USA_Parks_Thrive_Region2026,"U.S. Parks represents parks, gardens, and forests within...","U.S. Parks provides thousands of parks, gardens, and for...","Esri; TomTom North America, Inc.",NHunt73,public,,,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
31,natural-treasures,Outdoor Recreation,Parks,sublayer,0.0,e243bedec65443a0aba929442af1ecb8,USA_Parks_Thrive_Region2026,"U.S. Parks represents parks, gardens, and forests within...","U.S. Parks provides thousands of parks, gardens, and for...","Esri; TomTom North America, Inc.",NHunt73,public,,values shown are the item text. A sublayer's own summary...,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
32,natural-treasures,Outdoor Recreation,Parks and nature reserves,layer,NaN,09e74021fc5749a181e783a111905767,parks_nature_reserves_OSM_20260913,"Parks and nature reserves from Open Street Maps, Thrive ...",NaN,NaN,sara2263_thrive_geohub,public,"description, acknowledgments",,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
33,natural-treasures,Outdoor Recreation,Parks and nature reserves,sublayer,0.0,09e74021fc5749a181e783a111905767,parks_nature_reserves_OSM_20260913,"Parks and nature reserves from Open Street Maps, Thrive ...",NaN,NaN,sara2263_thrive_geohub,public,"description, acknowledgments",values shown are the item text. A sublayer's own summary...,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
34,natural-treasures,Outdoor Recreation,Hiking Trails,layer,NaN,18cacd1713e245b9916b53b7ef52f416,trails_county_name_added,NaN,NaN,NaN,sara2263_thrive_geohub,public,"summary, description, acknowledgments",,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
35,natural-treasures,Outdoor Recreation,Hiking Trails,sublayer,0.0,18cacd1713e245b9916b53b7ef52f416,trails_county_name_added,NaN,NaN,NaN,sara2263_thrive_geohub,public,"summary, description, acknowledgments",values shown are the item text. A sublayer's own summary...,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
36,natural-treasures,Outdoor Recreation,River Access,layer,NaN,48621d7af80e4b6cbcacf17afbfc6507,river_access_points_20260913,A merged copy of UTC's Tennessee River Access Locations ...,NaN,NaN,sara2263_thrive_geohub,public,"description, acknowledgments",,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...
37,natural-treasures,Outdoor Recreation,River Access,sublayer,0.0,48621d7af80e4b6cbcacf17afbfc6507,river_access_points_20260913,A merged copy of UTC's Tennessee River Access Locations ...,NaN,NaN,sara2263_thrive_geohub,public,"description, acknowledgments",values shown are the item text. A sublayer's own summary...,https://thrive-geohub.maps.arcgis.com/home/item.html?id=...

In [31]:
layers.to_excel( "../PY/layers_metadata.xlsx" )

## Accessing group layers

In [7]:
nta_map = maps['natural-treasures']

In [22]:
skip_titles = {'Cross Sector Data', 'Thrive County Boundaries',
               'Thrive watershed region', 'waterbodies'}

rows = []

map_item = gis.content.get( nta_map['mapId'])
wm = map_item.get_data()

wm

{'operationalLayers': [{'id': '19f8049271e-layer-46',
   'title': 'Cross Sector Data',
   'layers': [{'id': '19dd3d17b2b-layer-97',
     'title': 'parcels',
     'visibility': True,
     'layers': [{'id': '19dd1a4472c-layer-42',
       'title': 'Tennessee Property Boundaries Public Use',
       'url': 'https://services1.arcgis.com/YuVBSS7Y1of2Qud1/arcgis/rest/services/Tennessee_Property_Boundaries_Public_Use/FeatureServer/0',
       'visibility': False,
       'itemId': 'c4a29816b37f4824b71dad7b3c7a1b90',
       'layerType': 'ArcGISFeatureLayer',
       'showLabels': False,
       'layerDefinition': {'drawingInfo': {'renderer': {'type': 'simple',
          'visualVariables': [{'type': 'sizeInfo',
            'valueExpression': '$view.scale',
            'stops': [{'size': 0.21485714285714283, 'value': 2929},
             {'size': 0.10742857142857141, 'value': 9152},
             {'size': 0.05371428571428571, 'value': 36606},
             {'size': 0, 'value': 73213}],
            'target': 'outline'}],
          'symbol': {'type': 'esriSFS',
           'color': [0, 0, 0, 0],
           'outline': {'type': 'esriSLS',
            'color': [84, 84, 84, 64],
            'width': 0.188,
            'style': 'esriSLSSolid'},
           'style': 'esriSFSSolid'}}}}}],
     'layerType': 'GroupLayer',
     'visibilityMode': 'independent'}],
   'layerType': 'GroupLayer',
   'visibilityMode': 'independent'},
  {'id': '19dd37b8622-layer-91',
   'title': 'Land Use Change',
   'visibility': True,
   'layers': [{'id': '19f5d9bd54f-layer-54',
     'title': 'Developed Land Change 2004–2024, Percent Per Mile',
     'url': 'https://services3.arcgis.com/xpR2E2r2KmCE5hF3/arcgis/rest/services/hex_grid_1mi_landcover_change_watershed/FeatureServer/0',
     'visibility': False,
     'itemId': 'c8cb5376347542f597437060984d4069',
     'layerType': 'ArcGISFeatureLayer',
     'layerDefinition': {'fieldConfigurations': [{'alias': 'Agricultural land cover, percent change per mile hex bin',
        'name': 'ag_pct_chg',
        'fieldFormat': {'type': 'number',
         'maximumFractionDigits': 1,
         'minimumFractionDigits': 1,
         'useGrouping': 'always'}},
       {'alias': 'Developed land, percent change per mile hex bin',
        'name': 'dev_pct_chg',
        'fieldFormat': {'type': 'number',
         'maximumFractionDigits': 1,
         'minimumFractionDigits': 1,
         'useGrouping': 'always'}},
       {'name': 'hex_id',
        'fieldFormat': {'type': 'number', 'useGrouping': 'always'}},
       {'alias': 'Natural cover, percent change per hax bin',
        'name': 'nat_pct_chg',
        'fieldFormat': {'type': 'number',
         'maximumFractionDigits': 1,
         'minimumFractionDigits': 1,
         'useGrouping': 'always'}},
       {'name': 'Shape__Area',
        'fieldFormat': {'type': 'number',
         'minimumFractionDigits': 2,
         'useGrouping': 'always'}},
       {'name': 'Shape__Length',
        'fieldFormat': {'type': 'number',
         'minimumFractionDigits': 2,
         'useGrouping': 'always'}},
       {'name': 'total_px',
        'fieldFormat': {'type': 'number', 'useGrouping': 'always'}}],
      'drawingInfo': {'renderer': {'authoringInfo': {'type': 'classedColor'},
        'type': 'classBreaks',
        'visualVariables': [{'type': 'sizeInfo',
          'valueExpression': '$view.scale',
          'stops': [{'size': 1.0641082016054717, 'value': 32739},
           {'size': 0.5320541008027359, 'value': 102311},
           {'size': 0.39904057560205175, 'value': 409243},
           {'size': 0, 'value': 818487}],
          'target': 'outline'}],
        'classBreakInfos': [{'label': '10 - 15.5% Loss',
          'classMaxValue': -10,
          'symbol': {'type': 'esriSFS',
           'color': [169, 181, 77, 209],
           'outline': {'type': 'esriSLS',
            'color': [0, 0, 0, 0],
            'width': 0,
            'style': 'esriSLSSolid'},
           'style': 'esriSFSSolid'}},
         {'label': '1 - 10% Loss',
          'classMaxValue': -1,
          'symbol': {'type': 'esriSFS',
           'color': [212, 218, 166, 255],
           'outline': {'type': 'esriSLS',
            'color': [0, 0, 0, 0],
            'width': 0,
            'style': 'esriSLSSolid'},
           'style': 'esriSFSSolid'}},
         {'label': 'no change ',
          'classMaxValue': 1,
          'symbol': {'type': 'esriSFS',
           'color': [158, 202, 225, 0],
           'outline': {'type': 'esriSLS',
            'color': [0, 0, 0, 0],
            'width': 0,
            'style': 'esriSLSSolid'},
           'style': 'esriSFSSolid'}},
         {'label': '1 - 10 % Gain',
          'classMaxValue': 10,
          'symbol': {'type': 'esriSFS',
           'color': [255, 176, 107, 92],
           'outline': {'type': 'esriSLS',
            'color': [0, 0, 0, 0],
            'width': 0,
            'style': 'esriSLSSolid'},
           'style': 'esriSFSSolid'}},
         {'label': '10 - 25% Gain',
          'classMaxValue': 25,
          'symbol': {'type': 'esriSFS',
           'color': [247, 136, 67, 156],
           'outline': {'type': 'esriSLS',
            'color': [0, 0, 0, 0],
            'width': 0,
            'style': 'esriSLSSolid'},
           'style': 'esriSFSSolid'}},
         {'label': '25 - 50% Gain',
          'classMaxValue': 50,
          'symbol': {'type': 'esriSFS',
           'color': [255, 117, 31, 212],
           'outline': {'type': 'esriSLS',
            'color': [0, 0, 0, 0],
            'width': 0.51,
            'style': 'esriSLSSolid'},
           'style': 'esriSFSSolid'}},
         {'label': '50 – 82% Gain',
          'classMaxValue': 81.77193450927734,
          'symbol': {'type': 'esriSFS',
           'color': [255, 91, 15, 255],
           'outline': {'type': 'esriSLS',
            'color': [0, 0, 0, 0],
            'width': 0.517,
            'style': 'esriSLSSolid'},
           'style': 'esriSFSSolid'}}],
        'field': 'dev_pct_chg',
        'minValue': -15.326130867004395}}},
     'popupInfo': {'popupElements': [{'type': 'fields',
        'description': '',
        'fieldInfos': [{'fieldFormat': {'type': 'number',
           'maximumFractionDigits': 1,
           'minimumFractionDigits': 1,
           'useGrouping': 'always'},
          'fieldName': 'ag_pct_chg',
          'format': {'digitSeparator': True, 'places': 1},
          'isEditable': True,
          'label': 'Agricultural land cover, percent change per mile hex bin',
          'visible': True},
         {'fieldFormat': {'type': 'number',
           'maximumFractionDigits': 1,
           'minimumFractionDigits': 1,
           'useGrouping': 'always'},
          'fieldName': 'dev_pct_chg',
          'format': {'digitSeparator': True, 'places': 1},
          'isEditable': True,
          'label': 'Developed land, percent change per mile hex bin',
          'visible': True},
         {'fieldFormat': {'type': 'number',
           'maximumFractionDigits': 1,
           'minimumFractionDigits': 1,
           'useGrouping': 'always'},
          'fieldName': 'nat_pct_chg',
          'format': {'digitSeparator': True, 'places': 1},
          'isEditable': True,
          'label': 'Natural cover, percent change per hax bin',
          'visible': True}],
        'title': ''}],
      'expressionInfos': [{'name': 'expr0',
        'title': 'dev land change popup label',
        'expression': 'var percentValue = $feature.dev_pct_chg;\n\nif (IsEmpty(percentValue)) { return "No Data"; }\n\nvar labelType = "";\n// Changed from 1 to 0 to capture all positive/negative values\nif (percentValue < 0) {\n    labelType = "Loss";\n} else if (percentValue > 0) {\n    labelType = "Gain";\n}\n\nvar formattedValue = Text(percentValue, "#,###.0") + "%";\n\nif (labelType != "") {\n    return formattedValue + " (" + labelType + ")";\n} else {\n    return formattedValue;\n}\n',
        'returnType': 'string'}],
      'fieldInfos': [{'fieldName': 'ObjectId',
        'isEditable': False,
        'label': 'ObjectId',
        'visible': False},
       {'fieldName': 'ag_pct_chg',
        'format': {'digitSeparator': True, 'places': 1},
        'isEditable': True,
        'label': 'Agricultural land cover, percent change per mile hex bin',
        'visible': True},
       {'fieldName': 'dev_pct_chg',
        'format': {'digitSeparator': True, 'places': 1},
        'isEditable': True,
        'label': 'Developed land, percent change per mile hex bin',
        'visible': True},
       {'fieldName': 'hex_id',
        'format': {'digitSeparator': True},
        'isEditable': True,
        'label': 'hex_id',
        'visible': False},
       {'fieldName': 'nat_pct_chg',
        'format': {'digitSeparator': True, 'places': 1},
        'isEditable': True,
        'label': 'Natural cover, percent change per hax bin',
        'visible': True},
       {'fieldName': 'Shape__Area',
        'format': {'digitSeparator': True, 'places': 2},
        'isEditable': False,
        'label': 'Shape__Area',
        'visible': False},
       {'fieldName': 'Shape__Length',
        'format': {'digitSeparator': True, 'places': 2},
        'isEditable': False,
        'label': 'Shape__Length',
        'visible': False},
       {'fieldName': 'total_px',
        'format': {'digitSeparator': True},
        'isEditable': True,
        'label': 'total_px',
        'visible': False},
       {'fieldName': 'expression/expr0',
        'isEditable': True,
        'visible': False}],
      'title': 'Developed land use change by mile'}},
    {'id': '1a0a250ea04-layer-98',
     'title': 'Natural Cover Change 2004–2024 percent mile',
     'url': 'https://services3.arcgis.com/xpR2E2r2KmCE5hF3/arcgis/rest/services/hex_grid_1mi_landcover_change_watershed/FeatureServer/0',
     'visibility': False,
     'itemId': 'c8cb5376347542f597437060984d4069',
     'layerType': 'ArcGISFeatureLayer',
     'layerDefinition': {'fieldConfigurations': [{'alias': 'Agricultural Land Use Percent Change',
        'name': 'ag_pct_chg',
        'fieldFormat': {'type': 'number',
         'maximumFractionDigits': 1,
         'useGrouping': 'always'}},
       {'name': 'dev_pct_chg',
        'fieldFormat': {'type': 'number',
         'minimumFractionDigits': 2,
         'useGrouping': 'always'}},
       {'name': 'hex_id',
        'fieldFormat': {'type': 'number', 'useGrouping': 'always'}},
       {'alias': 'Natural Cover Change per Mile',
        'name': 'nat_pct_chg',
        'fieldFormat': {'type': 'number',
         'maximumFractionDigits': 1,
         'minimumFractionDigits': 1,
         'useGrouping': 'always'}},
       {'name': 'Shape__Area',
        'fieldFormat': {'type': 'number',
         'minimumFractionDigits': 2,
         'useGrouping': 'always'}},
       {'name': 'Shape__Length',
        'fieldFormat': {'type': 'number',
         'minimumFractionDigits': 2,
         'useGrouping': 'always'}},
       {'name': 'total_px',
        'fieldFormat': {'type': 'number', 'useGrouping': 'always'}},
       {'alias': 'ObjectId', 'name': 'ObjectId'}],
      'drawingInfo': {'renderer': {'authoringInfo': {'type': 'classedColor'},
        'type': 'classBreaks',
        'visualVariables': [{'type': 'sizeInfo',
          'valueExpression': '$view.scale',
          'stops': [{'size': 1.0814023146294625, 'value': 32739},
           {'size': 0.5407011573147312, 'value': 102311},
           {'size': 0.4055258679860484, 'value': 409243},
           {'size': 0, 'value': 818487}],
          'target': 'outline'}],
        'classBreakInfos': [{'label': '50 – 90 % loss',
          'classMaxValue': -50,
          'symbol': {'type': 'esriSFS',
           'color': [255, 124, 43, 255],
           'outline': {'type': 'esriSLS',
            'color': [0, 0, 0, 0],
            'width': 0,
            'style': 'esriSLSSolid'},
           'style': 'esriSFSSolid'}},
         {'label': '25 – 50 % loss',
          'classMaxValue': -25,
          'symbol': {'type': 'esriSFS',
           'color': [255, 124, 43, 219],
           'outline': {'type': 'esriSLS',
            'color': [0, 0, 0, 0],
            'width': 0,
            'style': 'esriSLSSolid'},
           'style': 'esriSFSSolid'}},
         {'label': '10 – 25 % loss',
          'classMaxValue': -10,
          'symbol': {'type': 'esriSFS',
           'color': [255, 176, 107, 232],
           'outline': {'type': 'esriSLS',
            'color': [0, 0, 0, 0],
            'width': 0,
            'style': 'esriSLSSolid'},
           'style': 'esriSFSSolid'}},
         {'label': '2 – 10 % loss',
          'classMaxValue': -2,
          'symbol': {'type': 'esriSFS',
           'color': [249, 180, 137, 117],
           'outline': {'type': 'esriSLS',
            'color': [0, 0, 0, 0],
            'width': 0,
            'style': 'esriSLSSolid'},
           'style': 'esriSFSSolid'}},
         {'label': 'no change',
          'classMaxValue': 2,
          'symbol': {'type': 'esriSFS',
           'color': [0, 0, 0, 0],
           'outline': {'type': 'esriSLS',
            'color': [0, 0, 0, 0],
            'width': 0,
            'style': 'esriSLSSolid'},
           'style': 'esriSFSSolid'}},
         {'label': '2 - 10 % gain',
          'classMaxValue': 10,
          'symbol': {'type': 'esriSFS',
           'color': [163, 192, 116, 125],
           'outline': {'type': 'esriSLS',
            'color': [0, 0, 0, 0],
            'width': 0,
            'style': 'esriSLSSolid'},
           'style': 'esriSFSSolid'}},
         {'label': '10 - 25 % gain',
          'classMaxValue': 25,
          'symbol': {'type': 'esriSFS',
           'color': [130, 169, 65, 186],
           'outline': {'type': 'esriSLS',
            'color': [0, 0, 0, 0],
            'width': 0,
            'style': 'esriSLSSolid'},
           'style': 'esriSFSSolid'}},
         {'label': '25 - 50 % gain',
          'classMaxValue': 50,
          'symbol': {'type': 'esriSFS',
           'color': [88, 140, 2, 255],
           'outline': {'type': 'esriSLS',
            'color': [0, 0, 0, 0],
            'width': 0,
            'style': 'esriSLSSolid'},
           'style': 'esriSFSSolid'}}],
        'field': 'nat_pct_chg',
        'minValue': -90.5660400390625}}},
     'popupInfo': {'popupElements': [{'type': 'fields',
        'description': '',
        'fieldInfos': [{'fieldName': 'expression/expr1',
          'isEditable': True,
          'visible': True}],
        'title': ''}],
      'expressionInfos': [{'name': 'expr0',
        'title': 'New expression',
        'expression': 'var percentValue = $feature.dev_pct_chg;\n\n// 1. Handle Null/Empty values safely to prevent map crashes\nif (IsEmpty(percentValue)) { return "No Data"; }\n\n// 2. Determine the label based on your threshold\n// NOTE: Change 1 to 0.01 if your field stores 100% as 1.0\nvar labelType = "";\nif (percentValue < -1) {\n    labelType = "Loss";\n} else if (percentValue > 1) {\n    labelType = "Gain";\n}\n// 3. Format the number safely (Formats 0 correctly as 0.0%)\nvar formattedValue = Text(percentValue, "#,###.0") + "%";\n\n// 4. Return the combined result\nif (labelType != "") {\n    return formattedValue + " (" + labelType + ")";\n} else {\n    return formattedValue;\n}\n\n',
        'returnType': 'string'},
       {'name': 'expr1',
        'title': 'Percent change per 1 mile hex grid',
        'expression': 'var percentValue = $feature.ag_pct_chg;\n\nif (IsEmpty(percentValue)) { return "No Data"; }\n\nvar labelType = "";\n// Changed from 1 to 0 to capture all positive/negative values\nif (percentValue < 0) {\n    labelType = "Loss";\n} else if (percentValue > 0) {\n    labelType = "Gain";\n}\n\nvar formattedValue = Text(percentValue, "#,###.0") + "%";\n\nif (labelType != "") {\n    return formattedValue + " (" + labelType + ")";\n} else {\n    return formattedValue;\n}\n',
        'returnType': 'string'}],
      'fieldInfos': [{'fieldName': 'ObjectId',
        'isEditable': False,
        'label': 'ObjectId',
        'visible': False},
       {'fieldName': 'ag_pct_chg',
        'format': {'digitSeparator': True, 'places': 1},
        'isEditable': True,
        'label': 'Agricultural Land Use Percent Change',
        'visible': False},
       {'fieldName': 'dev_pct_chg',
        'format': {'digitSeparator': True, 'places': 2},
        'isEditable': True,
        'label': 'dev_pct_chg',
        'visible': False},
       {'fieldName': 'hex_id',
        'format': {'digitSeparator': True},
        'isEditable': True,
        'label': 'hex_id',
        'visible': False},
       {'fieldName': 'nat_pct_chg',
        'format': {'digitSeparator': True, 'places': 1},
        'isEditable': True,
        'label': 'Natural Cover Change per Mile',
        'visible': False},
       {'fieldName': 'Shape__Area',
        'format': {'digitSeparator': True, 'places': 2},
        'isEditable': False,
        'label': 'Shape__Area',
        'visible': False},
       {'fieldName': 'Shape__Length',
        'format': {'digitSeparator': True, 'places': 2},
        'isEditable': False,
        'label': 'Shape__Length',
        'visible': False},
       {'fieldName': 'total_px',
        'format': {'digitSeparator': True},
        'isEditable': True,
        'label': 'total_px',
        'visible': False},
       {'fieldName': 'expression/expr0', 'isEditable': True, 'visible': False},
       {'fieldName': 'expression/expr1', 'isEditable': True, 'visible': True}],
      'title': 'Agriculture land use change'}},
    {'id': '19f63aa59c6-layer-40',
     'title': 'Land Use Change 2004 – 2024 60 meter resolution',
     'url': 'https://tiledimageservices3.arcgis.com/xpR2E2r2KmCE5hF3/arcgis/rest/services/landuse_change_watershed_boundary_2004_2024_60m_RAT_2/ImageServer',
     'visibility': False,
     'bandIds': [],
     'layerDefinition': {'drawingInfo': {'renderer': {'authoringInfo': {'colorRamp': {'type': 'multipart',
          'colorRamps': [{'type': 'algorithmic',
            'fromColor': [190, 190, 190, 255],
            'toColor': [255, 45, 8, 255]},
           {'type': 'algorithmic',
            'fromColor': [255, 45, 8, 255],
            'toColor': [255, 181, 61, 255]},
           {'type': 'algorithmic',
            'fromColor': [255, 181, 61, 255],
            'toColor': [255, 254, 52, 255]},
           {'type': 'algorithmic',
            'fromColor': [255, 254, 52, 255],
            'toColor': [0, 251, 50, 255]},
           {'type': 'algorithmic',
            'fromColor': [0, 251, 50, 255],
            'toColor': [255, 254, 52, 255]},
           {'type': 'algorithmic',
            'fromColor': [0, 253, 255, 255],
            'toColor': [0, 181, 255, 255]},
           {'type': 'algorithmic',
            'fromColor': [0, 181, 255, 255],
            'toColor': [26, 35, 253, 255]},
           {'type': 'algorithmic',
            'fromColor': [26, 35, 253, 255],
            'toColor': [255, 57, 251, 255]},
           {'type': 'algorithmic',
            'fromColor': [255, 57, 251, 255],
            'toColor': [255, 45, 8, 255]}]}},
        'type': 'uniqueValue',
        'field1': 'value',
        'uniqueValueGroups': [{'classes': [{'label': 'Developed -> Natural',
            'symbol': {'type': 'esriSFS',
             'color': [147, 162, 33, 255],
             'outline': {'type': 'esriSLS',
              'color': [0, 0, 0, 0],
              'width': 0,
              'style': 'esriSLSSolid'},
             'style': 'esriSFSSolid'},
            'values': [['12']]},
           {'label': 'Agriculture -> Natural',
            'symbol': {'type': 'esriSFS',
             'color': [163, 192, 116, 255],
             'outline': {'type': 'esriSLS',
              'color': [0, 0, 0, 0],
              'width': 0,
              'style': 'esriSLSSolid'},
             'style': 'esriSFSSolid'},
            'values': [['32']]},
           {'label': ' Developed -> Agriculture',
            'symbol': {'type': 'esriSFS',
             'color': [0, 143, 168, 255],
             'outline': {'type': 'esriSLS',
              'color': [0, 0, 0, 0],

In [23]:
for i in wm['operationalLayers']:

    print(f"""
    --------------------------
    {i['title']}, 
    {i['id']}, 
    {i['itemId'] if 'itemId' in i.keys() else 'No item id'}
    {i['layerType']}
    -------------------------
    """)

    --------------------------
    Cross Sector Data,
    19f8049271e-layer-46,
    No item id
    GroupLayer
    -------------------------


    --------------------------
    Land Use Change,
    19dd37b8622-layer-91,
    No item id
    GroupLayer
    -------------------------


    --------------------------
    Agriculture & Working Lands,
    19dca4c8b81-layer-18,
    No item id
    GroupLayer
    -------------------------


    --------------------------
    Biodiversity & Habitat,
    19f63a6445b-layer-39,
    No item id
    GroupLayer
    -------------------------


    --------------------------
    Protected Lands,
    19dca4b8b42-layer-16,
    d5ee129f6f9f477194721b2cda6f8049
    GroupLayer
    -------------------------


    --------------------------
    waterbodies,
    1a06dc0088f-layer-38,
    3ca7f70273f74d2a89982e5cecee4d98
    ArcGISFeatureLayer
    -------------------------


    --------------------------
    Water Resources,
    19dd381476c-layer-94,
    No item id
    GroupLayer
    -------------------------


    --------------------------
    Outdoor Recreation,
    19dca4bfb4a-layer-17,
    No item id
    GroupLayer
    -------------------------


    --------------------------
    Thrive County Boundaries,
    19d92026461-layer-7,
    f97879f1e2b3463597ad7a0e43248d92
    GeoJSON
    -------------------------


    --------------------------
    Thrive watershed region,
    1a09d29aa7c-layer-43,
    c44172df88b5420cbaef23f02acc1817
    ArcGISFeatureLayer
    -------------------------